Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-05, with the labels that each got.

#216 Updates runtime_block_states.dat to the new format
  block-states.ini
  src/main/java/cn/nukkit/level/GlobalBlockPalette.java
  src/main/java/cn/nukkit/nbt/stream/NBTInputStream.java
  src/main/resources/runtime_block_states.dat
  src/main/resources/runtime_block_states_overrides.dat
  src/test/java/test/BlockStateReader.java
  src/test/java/test/OverridesUpdater.java
Labels: Type: bug

#219 Fixes wrong or missing sounds
  src/main/java/cn/nukkit/block/BlockButton.java
  src/main/java/cn/nukkit/block/BlockDoor.java
Labels: Resolution: resolved, Type: bug

#202 [1.X] Fixes a condition error on BlockKelp.grow()
  src/main/java/cn/nukkit/block/BlockKelp.java
Labels: Status: Awaiting Merge, Type: bug

#224 [1.2.0] Fixes anvil not merging enchanted items correctly
  CHANGELOG.md
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#227 Adds PlayerJumpEvent and makes sugar canes call BlockGrowEvent
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockSugarcane.java
  src/main/java/cn/nukkit/event/player/PlayerJumpEvent.java
Labels: Resolution: resolved, Type: enhancement

#230 PN-87 Fix #228 Invalid enchantment order on anvil's results
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
Labels: Type: bug

#231 Cost calculation not applying bedrock edition reduction
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
Labels: Resolution: resolved, Type: bug

#233 The level is charged twice when operating an anvil
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
Labels: Resolution: resolved, Type: bug

#235 Fix wrong flags in MoveEntityAbsolutePacket + set onGround
  CHANGELOG.md
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/network/protocol/MoveEntityAbsolutePacket.java
Labels: Resolution: resolved, Type: bug

#234 Improves anvil security and reduces the risk of item loss
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
Labels: Type: bug

#236 Pushes 1.2.0.1-PN changes to 1.2.1.0-PN-SNAPSHOT
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/network/protocol/MoveEntityAbsolutePacket.java
Labels: Resolution: resolved, Type: bug

#241 Anvil fails to merge some enchantments because the ordering mismatches
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
Labels: Status: In Progress, Type: bug

#242 Adds equalsIgnoringEnchantmentOrder to Item and pull current 1.2.0.2-PN fixes
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
  src/main/java/cn/nukkit/item/Item.java
Labels: Type: bug, Type: enhancement

#243 Thorns and punch weights were incorrect
  CHANGELOG.md
  src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java
  src/main/java/cn/nukkit/item/enchantment/bow/EnchantmentBowKnockback.java
Labels: Type: bug

#246 Fixes some checks in anvil and some wrong enchantment compatibility rules
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentDurability.java
  src/main/java/cn/nukkit/item/enchantment/bow/EnchantmentBowInfinity.java
  src/main/java/cn/nukkit/item/enchantment/trident/EnchantmentTridentRiptide.java
Labels: Resolution: resolved, Type: bug

#244 Fixes anvil enchantment compatibility conditions
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/item/enchantment/Enchantment.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentDurability.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentEfficiency.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentSilkTouch.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java
  src/main/java/cn/nukkit/item/enchantment/bow/EnchantmentBowInfinity.java
  src/main/java/cn/nukkit/item/enchantment/damage/EnchantmentDamage.java
  src/main/java/cn/nukkit/item/enchantment/trident/EnchantmentTridentRiptide.java
Labels: Resolution: resolved, Type: bug

#247 Makes the server log when it finds an unknown BlockId:Meta combination
  CHANGELOG.md
  src/main/java/cn/nukkit/level/GlobalBlockPalette.java
Labels: Resolution: resolved, Type: enhancement

#248 Ignores the meta in air blocks when rendering to the client
  CHANGELOG.md
  src/main/java/cn/nukkit/level/GlobalBlockPalette.java
Labels: Resolution: resolved, Type: bug

#249 Fixes the command: /tp player 0 1 2
  CHANGELOG.md
  src/main/java/cn/nukkit/command/defaults/TeleportCommand.java
Labels: Resolution: resolved, Type: bug

#250 Fix Stripping old full bark log results in a wrong block
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockWood.java
  src/main/java/cn/nukkit/block/BlockWood2.java
Labels: Resolution: resolved, Type: bug

#251 Wrong Packed and Blue Ice break time with hands
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockIcePacked.java
Labels: Resolution: resolved, Type: bug

#252 Fixes wrong explosion behaviour with waterlogged block
  CHANGELOG.md
  src/main/java/cn/nukkit/level/Explosion.java
Labels: Type: bug

#253 Fixes BlockLeaves's random update logic spamming packets and LeavesDecayEvent being called when the leaves won't decay
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockLeaves.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#255 Fix /status information in /debugpaste not being collected
  CHANGELOG.md
  src/main/java/cn/nukkit/command/defaults/DebugPasteCommand.java
  src/main/java/cn/nukkit/utils/Watchdog.java
Labels: Resolution: resolved, Type: bug

#256 Move CapturingCommandSender to its own public class
  CHANGELOG.md
Labels: Resolution: resolved, Type: enhancement

#258 Fixes leaves log scanning logic
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockLeaves.java
Labels: Resolution: resolved, Type: bug

#259 Adds Hash.hashBlock(Vector3)
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockLeaves.java
  src/main/java/cn/nukkit/utils/Hash.java
Labels: Resolution: resolved, Type: enhancement

#260 Fixes issues with end crystals, block's inventory drops by explosions and LoginPacket's protocol check
  CHANGELOG.md
  src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java
  src/main/java/cn/nukkit/level/Explosion.java
  src/main/java/cn/nukkit/network/protocol/LoginPacket.java
Labels: Resolution: resolved, Type: bug

#261 Adds getter for checkMovement and a the reason to kick messages
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java
  src/main/java/cn/nukkit/level/Explosion.java
  src/main/java/cn/nukkit/network/protocol/LoginPacket.java
Labels: Resolution: resolved, Type: enhancement

#262 Fixes the sugarcane update logic
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockSugarcane.java
  src/main/java/cn/nukkit/item/ItemBucket.java
Labels: Resolution: resolved, Type: bug

#263 Fixes Disconnect messages not reaching the player sometimes
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
Labels: Type: bug

#264 Fixes fishing hooks not attaching to entities.
  CHANGELOG.md
  src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
Labels: Resolution: resolved, Type: bug

#268 Enhances the level up sound and makes /xp make sound too
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/command/defaults/XpCommand.java
Labels: Resolution: resolved, Type: enhancement

#269 Removes fishing hook without player
  CHANGELOG.md
  src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
Labels: Resolution: resolved, Type: bug

#271 Fixes fishing hooks using mount instead of DATA_TARGET_EID
  src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
Labels: Resolution: resolved, Type: bug

#273 Fix item losses when player gets disconnected with items in open fake inventories
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/inventory/BeaconInventory.java
  src/main/java/cn/nukkit/inventory/EnchantInventory.java
  src/main/java/cn/nukkit/inventory/FakeBlockUIComponent.java
  src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
  src/main/java/cn/nukkit/inventory/StonecutterInventory.java
Labels: Resolution: resolved, Type: bug

#274 Pulls> Don't run checkInteractNearby on every tick
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
Labels: Type: bug

#275 Adds banner patterns and new annotations
  CHANGELOG.md
  src/main/java/cn/nukkit/api/DeprecationDetails.java
  src/main/java/cn/nukkit/api/PowerNukkitOnly.java
  src/main/java/cn/nukkit/api/Since.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemBannerPattern.java
  src/main/java/cn/nukkit/item/ItemID.java
Labels: Type: enhancement

#276 Adds Block.afterRemoval(), called when the block is replaced
  CHANGELOG.md
  src/main/java/cn/nukkit/api/DeprecationDetails.java
  src/main/java/cn/nukkit/api/PowerNukkitOnly.java
  src/main/java/cn/nukkit/api/Since.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: enhancement

#277 Fixes behives+bees+creative and add new methods to Block
  CHANGELOG.md
  src/main/java/cn/nukkit/api/DeprecationDetails.java
  src/main/java/cn/nukkit/api/PowerNukkitOnly.java
  src/main/java/cn/nukkit/api/Since.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBeehive.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#278 Fixes what happens when you replace the sugarcane's water with an other block
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockWater.java
  src/main/java/cn/nukkit/item/ItemBucket.java
Labels: Resolution: resolved, Type: bug

#279 Fixes EntityPortalEnterEvent not being fired when entering end portals
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/api/PowerNukkitOnly.java
  src/main/java/cn/nukkit/block/BlockEndPortal.java
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Resolution: resolved, Type: bug
