Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-02, with the labels that each got.

#128 Migrates the lingering potion and area effect cloud implementation to v2.0
  src/main/java/cn/nukkit/entity/data/EntityData.java
  src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
  src/main/java/cn/nukkit/entity/impl/projectile/EntityLingeringPotion.java
  src/main/java/cn/nukkit/entity/impl/projectile/EntitySplashPotion.java
  src/main/java/cn/nukkit/entity/misc/AreaEffectCloud.java
  src/main/java/cn/nukkit/item/ItemPotionLingering.java
  src/main/java/cn/nukkit/registry/EntityRegistry.java
Labels: Type: enhancement

#133 [1.X-PN] Changes the logo and banner to PowerNukkit
  .github/images/banner.png
  .github/images/logo.png
Labels: Type: enhancement

#129 Fix campfire or bamboo can be placed inside of water & fix overScaffolding check
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBamboo.java
  src/main/java/cn/nukkit/block/BlockBambooSapling.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockTurtleEgg.java
Labels: Type: bug

#136 Updates the project files based on the master branch
  .github/ISSUE_TEMPLATE.md
  .github/workflows/maven.yml
  CHANGELOG.md
  Dockerfile
  Jenkinsfile
  README.md
  pom.xml
Labels: Type: enhancement

#134 [2.X-PN] Changes the logo and banner to PowerNukkit
  .github/images/banner.png
  .github/images/logo.png
Labels: Resolution: resolved, Type: enhancement

#137 Removes the tests badges and changes the build status to GitHub Actions
  .github/workflows/maven.yml
  README.md
Labels: Type: enhancement

#138 Makes the GitHub Actions badge link to the build history
  README.md
Labels: Resolution: resolved, Type: enhancement

#139 Merge v2.0/item/potion/undeads into 2.0-migration
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityDrowned.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityHusk.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityPhantom.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntitySkeleton.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityStray.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityWither.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityWitherSkeleton.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombie.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombiePigman.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombieVillager.java
  src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
  src/main/java/cn/nukkit/entity/impl/passive/EntitySkeletonHorse.java
  src/main/java/cn/nukkit/entity/impl/passive/EntityZombieHorse.java
  src/main/java/cn/nukkit/potion/Potion.java
Labels: Type: bug

#132 Fixed EntityAreaEffectCloud detecting not alive entities
  src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
Labels: Type: bug

#144 Update the v2.0-PN branch from NukkitX
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/data/EntityData.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityDrowned.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityHusk.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityPhantom.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntitySkeleton.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityStray.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityWither.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityWitherSkeleton.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombie.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombiePigman.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombieVillager.java
  src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
  src/main/java/cn/nukkit/entity/impl/passive/EntitySkeletonHorse.java
  src/main/java/cn/nukkit/entity/impl/passive/EntityZombieHorse.java
  src/main/java/cn/nukkit/entity/impl/projectile/EntityLingeringPotion.java
  src/main/java/cn/nukkit/entity/impl/projectile/EntitySplashPotion.java
  src/main/java/cn/nukkit/entity/misc/AreaEffectCloud.java
  src/main/java/cn/nukkit/item/ItemPotionLingering.java
  src/main/java/cn/nukkit/potion/Potion.java
  src/main/java/cn/nukkit/registry/EntityRegistry.java
Labels: Type: bug, Type: enhancement

#140 Replicate Area Effect Cloud and Lingering potion fixes to V1.X
  CHANGELOG.md
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/item/EntityAreaEffectCloud.java
  src/main/java/cn/nukkit/entity/mob/EntityDrowned.java
  src/main/java/cn/nukkit/entity/mob/EntityHusk.java
  src/main/java/cn/nukkit/entity/mob/EntityPhantom.java
  src/main/java/cn/nukkit/entity/mob/EntitySkeleton.java
  src/main/java/cn/nukkit/entity/mob/EntityStray.java
  src/main/java/cn/nukkit/entity/mob/EntityWither.java
  src/main/java/cn/nukkit/entity/mob/EntityWitherSkeleton.java
  src/main/java/cn/nukkit/entity/mob/EntityZombie.java
  src/main/java/cn/nukkit/entity/mob/EntityZombiePigman.java
  src/main/java/cn/nukkit/entity/mob/EntityZombieVillager.java
  src/main/java/cn/nukkit/entity/mob/EntityZombieVillagerV1.java
  src/main/java/cn/nukkit/entity/passive/EntitySkeletonHorse.java
  src/main/java/cn/nukkit/entity/passive/EntityZombieHorse.java
  src/main/java/cn/nukkit/potion/Potion.java
Labels: Type: bug

#143 Adding Blue Ice to Nukkit 2.0
  src/main/java/cn/nukkit/block/BlockBlueIce.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Type: enhancement

#146 Migrates the barrel block implementation to v2.0
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockBarrel.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityBarrel.java
  src/main/java/cn/nukkit/inventory/BarrelInventory.java
  src/main/java/cn/nukkit/inventory/InventoryType.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Status: Awaiting NukkitX, Type: enhancement

#147 Fix BlockEntities not being saved when it should be
  src/main/java/cn/nukkit/level/provider/leveldb/serializer/BlockEntitySerializer.java
Labels: Status: Awaiting NukkitX, Type: bug

#149 Migrates the smooth stone block implementation to v2.0
  src/main/java/cn/nukkit/block/BlockSmoothStone.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Status: Awaiting NukkitX, Type: enhancement

#159 Pull the commits from NukkitX:2.0 into v2.0/block/ice-block/fixing-on-break
  src/main/java/cn/nukkit/block/BlockBarrier.java
  src/main/java/cn/nukkit/block/BlockBlueIce.java
  src/main/java/cn/nukkit/block/BlockSmoothStone.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityDrowned.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityHusk.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityPhantom.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntitySkeleton.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityStray.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityWither.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityWitherSkeleton.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombie.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombiePigman.java
  src/main/java/cn/nukkit/entity/impl/hostile/EntityZombieVillager.java
  src/main/java/cn/nukkit/entity/impl/misc/EntityAreaEffectCloud.java
  src/main/java/cn/nukkit/entity/impl/passive/EntitySkeletonHorse.java
  src/main/java/cn/nukkit/entity/impl/passive/EntityZombieHorse.java
  src/main/java/cn/nukkit/level/provider/leveldb/serializer/BlockEntitySerializer.java
  src/main/java/cn/nukkit/potion/Potion.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Type: bug, Type: enhancement

#152 Fixes the blue_ice blast resistance in v1.x
  src/main/java/cn/nukkit/block/BlockBlueIce.java
Labels: Resolution: resolved, Type: bug

#155 Fix the ice break conditions and adds the player on parameters of onBreak of Block.
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBlueIce.java
  src/main/java/cn/nukkit/block/BlockIce.java
  src/main/java/cn/nukkit/block/BlockIcePacked.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Resolution: resolved, Type: enhancement

#162 Migrated Dried Kelp Block
  src/main/java/cn/nukkit/block/BlockDriedKelp.java
  src/main/java/cn/nukkit/inventory/Fuel.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: enhancement

#165 Fix the dropped button's damage value when a button is broken
  src/main/java/cn/nukkit/block/BlockButton.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: bug

#166 Fix stone_button break time and dropping without pickaxe
  src/main/java/cn/nukkit/block/BlockButtonStone.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: bug

#154 Migrates the Trapdoor blocks
  src/main/java/cn/nukkit/block/BlockTrapdooDarkOak.java
  src/main/java/cn/nukkit/block/BlockTrapdoorAcacia.java
  src/main/java/cn/nukkit/block/BlockTrapdoorBirch.java
  src/main/java/cn/nukkit/block/BlockTrapdoorJungle.java
  src/main/java/cn/nukkit/block/BlockTrapdoorSpruce.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Type: enhancement

#158 Fixes the trapdoor behaving incorrectly when it receives a redstone signal
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: bug

#170 [1.X] Fixes trapdoor behaviour on redstone signal
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
Labels: Resolution: resolved, Type: bug

#163 Added other wooden button types
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Status: Awaiting NukkitX, Type: enhancement

#164 Added other wooden pressure plate types.
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: enhancement

#173 [2.X] Updates the 2.0-migration branch with NukkitX 2.0 fixes.
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockDriedKelp.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
  src/main/java/cn/nukkit/block/BlockTrapdoorIron.java
  src/main/java/cn/nukkit/block/BlockWater.java
  src/main/java/cn/nukkit/blockentity/BlockEntityCampfire.java
  src/main/java/cn/nukkit/item/ItemBucket.java
  src/main/java/cn/nukkit/level/BlockPosition.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/chunk/ChunkSection.java
  src/main/java/cn/nukkit/level/chunk/UnsafeChunk.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Type: bug, Type: enhancement

#172 [1.X] Updates the master branch with NukkitX fixes.
  src/main/java/cn/nukkit/IPlayer.java
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
  src/main/java/cn/nukkit/inventory/PlayerInventory.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Status: Awaiting Review, Type: bug

#176 Updates the 2.0-migration branch with NukkitX 2.0 fixes.
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockChest.java
  src/main/java/cn/nukkit/block/BlockFurnaceBurning.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityBlastFurnace.java
  src/main/java/cn/nukkit/blockentity/BlockEntityCampfire.java
  src/main/java/cn/nukkit/blockentity/BlockEntityFurnace.java
  src/main/java/cn/nukkit/blockentity/BlockEntitySmoker.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/inventory/FurnaceInventory.java
  src/main/java/cn/nukkit/inventory/FurnaceRecipe.java
  src/main/java/cn/nukkit/inventory/InventoryType.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Resolution: resolved, Type: enhancement

#180 Implements Lectern Block
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockLectern.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityLectern.java
  src/main/java/cn/nukkit/event/block/LecternDropBookEvent.java
  src/main/java/cn/nukkit/event/block/LecternPageChangeEvent.java
  src/main/java/cn/nukkit/event/block/LecternPlaceBookEvent.java
  src/main/java/cn/nukkit/player/Player.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Status: Awaiting NukkitX, Type: enhancement

#177 Fixes lever switch sound pitch
  src/main/java/cn/nukkit/block/BlockLever.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: bug

#179 Migrates the Stripped Log Blocks
  src/main/java/cn/nukkit/block/BlockLog.java
  src/main/java/cn/nukkit/block/BlockStrippedLog.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: enhancement

#178 Migrate new sign types
  src/main/java/cn/nukkit/block/BlockSignPost.java
  src/main/java/cn/nukkit/block/BlockWallSign.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
  src/main/java/cn/nukkit/registry/ItemRegistry.java
Labels: Resolution: resolved, Type: enhancement

#188 [2.0] Fix a startup error
  src/main/java/cn/nukkit/level/LevelData.java
  src/main/java/cn/nukkit/nbt/tag/StringTag.java
Labels: Type: bug

#190 Fixes wrong Stripped Log Block damage
  src/main/java/cn/nukkit/block/BlockStrippedLog.java
Labels: Resolution: resolved, Status: Awaiting NukkitX, Type: bug

#189 Fix two critical packet issues
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/registry/ItemRegistry.java
Labels: Resolution: resolved, Type: bug

#200 Updates the 2.0-migration branch with NukkitX 2.0 fixes
  src/main/java/cn/nukkit/block/BlockBed.java
  src/main/java/cn/nukkit/block/BlockLight.java
  src/main/java/cn/nukkit/player/Player.java
Labels: Type: bug, Type: enhancement

#201 [1.X] Updates the master branch with NukkitX fixes.
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java
  src/main/java/cn/nukkit/entity/item/EntityItem.java
  src/main/java/cn/nukkit/entity/item/EntityXPOrb.java
  src/main/java/cn/nukkit/level/Explosion.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Type: bug

#198 Migrating Honey
  src/main/java/cn/nukkit/item/ItemHoneyBottle.java
  src/main/java/cn/nukkit/item/food/Food.java
  src/main/java/cn/nukkit/item/food/FoodHoney.java
  src/main/java/cn/nukkit/registry/ItemRegistry.java
Labels: Resolution: resolved, Type: enhancement

#204 Fix crash when waterlogged flowing water meets still water
  src/main/java/cn/nukkit/block/BlockLava.java
  src/main/java/cn/nukkit/block/BlockLavaStill.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockWater.java
  src/main/java/cn/nukkit/block/BlockWaterStill.java
  src/main/java/cn/nukkit/registry/BlockRegistry.java
Labels: Resolution: resolved, Type: bug
