Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-12, with the labels that each got.

#785 Totem give Fire Resistance I not II
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Resolution: resolved, Type: bug

#784 Update Bee Nest block color
  src/main/java/cn/nukkit/block/BlockBeeNest.java
Labels: Type: enhancement

#731 Fix error when changing delay of repeater
  src/main/java/cn/nukkit/block/BlockRedstoneDiode.java
  src/main/java/cn/nukkit/block/BlockRedstoneRepeater.java
  src/main/java/cn/nukkit/block/BlockRedstoneRepeaterPowered.java
  src/main/java/cn/nukkit/block/BlockRedstoneRepeaterUnpowered.java
Labels: Status: Awaiting Review, Type: bug

#666 Add more cauldron behavior
  src/main/java/cn/nukkit/block/BlockCauldron.java
  src/main/java/cn/nukkit/item/ItemBanner.java
Labels: Status: Awaiting Review, Type: enhancement

#775 Fix and update composter
  src/main/java/cn/nukkit/block/BlockComposter.java
Labels: Status: In Progress, Type: enhancement

#735 Makes hoppers can pull and push items to a composter
  src/main/java/cn/nukkit/block/BlockComposter.java
  src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
  src/main/java/cn/nukkit/event/block/ComposterEmptyEvent.java
  src/main/java/cn/nukkit/event/block/ComposterFillEvent.java
Labels: Status: In Progress, Type: bug

#812 Protocol bump
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
Labels: Status: Awaiting Review, Type: compatibility

#815 Update Grass Path (Dirt Path)
  src/main/java/cn/nukkit/block/BlockDirt.java
  src/main/java/cn/nukkit/block/BlockGrass.java
  src/main/java/cn/nukkit/block/BlockGrassPath.java
  src/main/java/cn/nukkit/block/BlockMycelium.java
  src/main/java/cn/nukkit/block/BlockPodzol.java
Labels: Status: Awaiting Review, Tag : Minecraft Version Update, Type: compatibility, Type: enhancement

#831 Fix human NPCs (and my player heads plugin)
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
Labels: Status: Awaiting Merge, Type: bug

#818 Fix #781 (torch with charcoal)
  src/main/resources/recipes.json
Labels: Status: Awaiting Review, Type: bug, Waiting for Code Owner

#763 Check pageText is out of range (text length > 256)
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/item/ItemBookWritable.java
Labels: Implementation: Item, Status: Awaiting Merge, Type: bug

#712 Fix Block.registerBlockImplementation error message
  src/main/java/cn/nukkit/block/Block.java
Labels: Status: Awaiting Merge, Type: bug

#838 Fix Sweet Berry Bush drops (Fix duplication problem)
  src/main/java/cn/nukkit/block/BlockSweetBerryBush.java
Labels: Resolution: resolved, Type: bug

#846 [v1.3.x] Pull changes from upstream (master)
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
  src/main/java/cn/nukkit/entity/projectile/EntitySnowball.java
Labels: Resolution: resolved, Type: bug, Type: enhancement
