Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-08, with the labels that each got.

#431 Adjusting the docker cloud builds
  .dockerignore
  Dockerfile
  hooks/post_checkout
Labels: Resolution: resolved, Type: Tool

#432 Fix Rail Placement Issues
  src/main/java/cn/nukkit/block/BlockRail.java
Labels: Type: bug

#438 Fixes firework being overridden with a black creeper face
  src/main/java/cn/nukkit/dispenser/FireworksDispenseBehavior.java
  src/main/java/cn/nukkit/entity/data/EntityMetadata.java
  src/main/java/cn/nukkit/entity/item/EntityFirework.java
  src/main/java/cn/nukkit/item/ItemFirework.java
Labels: Resolution: resolved, Type: bug

#439 Fix: Spectators with OP can still break blocks (client-side)
  src/main/java/cn/nukkit/AdventureSettings.java
Labels: Resolution: resolved, Type: bug

#403 Fix for block activation whilst sneaking
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug

#440 Fixes some issues that are fixable in 1.3.1.2-PN
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockChorusFlower.java
  src/main/java/cn/nukkit/block/BlockChorusPlant.java
  src/main/java/cn/nukkit/block/BlockFlowerPot.java
  src/main/java/cn/nukkit/block/BlockRedstoneDiode.java
  src/main/java/cn/nukkit/block/BlockSlab.java
  src/main/java/cn/nukkit/block/BlockStairs.java
  src/main/java/cn/nukkit/blockentity/BlockEntityDaylightDetector.java
  src/main/java/cn/nukkit/command/CommandSender.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
  src/main/java/cn/nukkit/item/ItemFlintSteel.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/utils/Watchdog.java
Labels: Type: bug

#446 Fix fire, iron doors, comparators, redstone wire, minecarts, and boat
  src/main/java/cn/nukkit/block/BlockDoor.java
  src/main/java/cn/nukkit/block/BlockFire.java
  src/main/java/cn/nukkit/block/BlockRedstoneComparator.java
  src/main/java/cn/nukkit/block/BlockRedstoneWire.java
  src/main/java/cn/nukkit/entity/item/EntityBoat.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
  src/main/java/cn/nukkit/entity/projectile/EntitySnowball.java
Labels: Resolution: resolved, Type: bug

#449 Update Noteblock Get Instrument Types
  src/main/java/cn/nukkit/block/BlockNoteblock.java
Labels: Resolution: resolved, Type: bug

#450 Improve Fire charge Ignite
  src/main/java/cn/nukkit/item/ItemFireCharge.java
Labels: Resolution: resolved, Type: bug

#451 Add Rabbit Hide
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemRabbitHide.java
Labels: Resolution: resolved, Type: enhancement

#453 Add Popped Chorus Fruit
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemChorusFruitPopped.java
Labels: Resolution: resolved, Type: enhancement

#454 Add Dragon's Breath
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemDragonBreath.java
Labels: Resolution: resolved, Type: enhancement

#457 Fix darkoak and acacia leaves making waves on block update and leaves drop rates
  runtime_block_states.dat.dump.txt
  src/main/java/cn/nukkit/block/BlockLeaves.java
  src/main/java/cn/nukkit/block/BlockLeaves2.java
  src/main/java/cn/nukkit/level/format/updater/ChunkUpdater.java
  src/main/java/cn/nukkit/level/format/updater/NewLeafUpdater.java
  src/main/resources/runtime_block_states_overrides.dat
  src/test/java/test/OverridesUpdater.java
Labels: Resolution: resolved, Type: bug

#392 Implements allow, deny and border blocks
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockAllow.java
  src/main/java/cn/nukkit/block/BlockBorder.java
  src/main/java/cn/nukkit/block/BlockDeny.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockWall.java
  src/main/java/cn/nukkit/block/BlockWallBase.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/ChunkSection.java
  src/main/java/cn/nukkit/level/format/FullChunk.java
  src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
  src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
  src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
  src/main/java/cn/nukkit/level/format/generic/EmptyChunkSection.java
  src/main/resources/block_ids.csv
  src/test/java/cn/nukkit/level/format/anvil/util/BlockStorageTest.java
  src/test/java/cn/nukkit/level/format/generic/BaseChunkTest.java
Labels: Resolution: resolved, Type: enhancement

#469 Fix: Reconnecting while in the nether shows orverworld sky
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug

#475 Improved conf and batch packet error handing
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/utils/Config.java
Labels: Resolution: resolved, Type: enhancement

#468 Add Piglin Brute
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/mob/EntityPiglinBrute.java
  src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
Labels: Resolution: resolved, Type: enhancement

#474 Add Lead without Functionality
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemLead.java
Labels: Resolution: resolved, Status: Awaiting Merge, Type: enhancement

#476 Wall Connection Update
  src/main/java/cn/nukkit/block/BlockWallBase.java
Labels: Resolution: resolved, Type: enhancement

#480 Add Structure Block without Functionality
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockStructure.java
Labels: Resolution: resolved, Type: enhancement

#488 Fix melon not breaking when pushed by piston
  src/main/java/cn/nukkit/block/BlockMelon.java
Labels: Resolution: resolved, Type: bug

#487 Add Nether Gold Ore
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockNetherOreGold.java
Labels: Resolution: resolved, Type: enhancement

#489 Add Crying Obsidian
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockObsidianCrying.java
Labels: Status: Awaiting Merge, Type: enhancement

#498 Fix: players can use buckets in adventure mode
  src/main/java/cn/nukkit/item/ItemBucket.java
Labels: Resolution: resolved, Type: bug

#493 Add Structure Void
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockStructureVoid.java
Labels: Resolution: resolved, Type: enhancement

#508 Fixes structure void implementation and merges with bleeding
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockSnowLayer.java
  src/main/java/cn/nukkit/block/BlockStructureVoid.java
  src/main/java/cn/nukkit/blockproperty/value/StructureVoidType.java
  src/main/resources/block_ids.csv
Labels: Resolution: resolved, Type: enhancement

#510 Implement soul_campfire and fix campfire break time
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockCampfireSoul.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemCampfireSoul.java
  src/main/java/cn/nukkit/item/ItemID.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#519 Implement Soul Fire and fix fling and steel not damaging
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockFire.java
  src/main/java/cn/nukkit/block/BlockFireSoul.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/item/ItemFlintSteel.java
Labels: Status: In Progress, Type: enhancement

#516 Adds lodestone, lodestone_compass and related packets
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockLodestone.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityLodestone.java
  src/main/java/cn/nukkit/command/defaults/SetBlockCommand.java
  src/main/java/cn/nukkit/entity/EntityHumanType.java
  src/main/java/cn/nukkit/inventory/BaseInventory.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemCompassLodestone.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/level/Position.java
  src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorGroundCover.java
  src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorOre.java
  src/main/java/cn/nukkit/math/Vector3.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/protocol/ItemStackRequestPacket.java
  src/main/java/cn/nukkit/network/protocol/ItemStackResponsePacket.java
  src/main/java/cn/nukkit/network/protocol/PositionTrackingDBClientRequestPacket.java
  src/main/java/cn/nukkit/network/protocol/PositionTrackingDBServerBroadcastPacket.java
  src/main/java/cn/nukkit/positiontracking/NamedPosition.java
  src/main/java/cn/nukkit/positiontracking/PositionTracking.java
  src/main/java/cn/nukkit/positiontracking/PositionTrackingService.java
  src/main/java/cn/nukkit/positiontracking/PositionTrackingStorage.java
  src/test/java/cn/nukkit/positiontracking/PositionTrackingStorageTest.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#524 Add Iron Nugget
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemNuggetIron.java
Labels: Resolution: resolved, Type: enhancement

#532 A few enhancements for plugin developers
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockCauldron.java
  src/main/java/cn/nukkit/block/BlockHoney.java
  src/main/java/cn/nukkit/block/BlockIce.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockSlime.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/plugin/PluginBase.java
  src/main/java/cn/nukkit/utils/Utils.java
Labels: Resolution: resolved, Type: enhancement

#537 Improves the method that get items from string
  src/main/java/cn/nukkit/item/Item.java
Labels: Type: enhancement

#492 Improve Gravel, Sea Lantern, Tall grass, Wheat Block Drop Rates and Add Fortune Drops
  src/main/java/cn/nukkit/block/BlockGravel.java
  src/main/java/cn/nukkit/block/BlockSeaLantern.java
  src/main/java/cn/nukkit/block/BlockTallGrass.java
  src/main/java/cn/nukkit/block/BlockWheat.java
Labels: Resolution: resolved, Type: bug

#385 Updating Sound Method
  src/main/java/cn/nukkit/block/BlockCauldronLava.java
  src/main/java/cn/nukkit/block/BlockEndPortalFrame.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockPistonBase.java
  src/main/java/cn/nukkit/block/BlockTurtleEgg.java
  src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java
  src/main/java/cn/nukkit/blockentity/BlockEntityBrewingStand.java
  src/main/java/cn/nukkit/blockentity/BlockEntityJukebox.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
  src/main/java/cn/nukkit/entity/item/EntityExpBottle.java
  src/main/java/cn/nukkit/entity/item/EntityFirework.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartTNT.java
  src/main/java/cn/nukkit/entity/item/EntityPotion.java
  src/main/java/cn/nukkit/entity/item/EntityPrimedTNT.java
  src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java
  src/main/java/cn/nukkit/entity/weather/EntityLightning.java
  src/main/java/cn/nukkit/inventory/ChestInventory.java
  src/main/java/cn/nukkit/inventory/DoubleChestInventory.java
  src/main/java/cn/nukkit/inventory/PlayerEnderChestInventory.java
  src/main/java/cn/nukkit/inventory/ShulkerBoxInventory.java
  src/main/java/cn/nukkit/item/ItemArmor.java
  src/main/java/cn/nukkit/item/ItemBow.java
  src/main/java/cn/nukkit/item/ItemBucket.java
  src/main/java/cn/nukkit/item/ItemFlintSteel.java
  src/main/java/cn/nukkit/item/ItemTrident.java
  src/main/java/cn/nukkit/level/Explosion.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
Labels: Resolution: resolved, Type: enhancement

#542 Add Chain Armor Anvil Repair
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
Labels: Resolution: resolved, Type: bug
