Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-06, with the labels that each got.

#281 Fixes levers and buttons don't replace the snow layers
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockButton.java
  src/main/java/cn/nukkit/block/BlockLever.java
Labels: Resolution: resolved, Type: bug

#284 Removes the PowerNukkit proxy class, it was not cool
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/item/enchantment/Enchantment.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentDurability.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentEfficiency.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentSilkTouch.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentThorns.java
  src/main/java/cn/nukkit/item/enchantment/damage/EnchantmentDamage.java
Labels: Type: enhancement

#285 Pull NukkitX 1.X changes into 1.2.1.0-PN-SNAPSHOT
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockChorusFlower.java
  src/main/java/cn/nukkit/block/BlockChorusPlant.java
  src/main/java/cn/nukkit/block/BlockFenceNetherBrick.java
  src/main/java/cn/nukkit/block/BlockPrismarine.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartChest.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartHopper.java
  src/main/java/cn/nukkit/entity/passive/EntityChicken.java
  src/main/java/cn/nukkit/entity/passive/EntityCow.java
  src/main/java/cn/nukkit/entity/passive/EntityPig.java
  src/main/java/cn/nukkit/entity/passive/EntityRabbit.java
  src/main/java/cn/nukkit/entity/passive/EntitySheep.java
  src/main/java/cn/nukkit/entity/projectile/EntityEnderPearl.java
  src/main/java/cn/nukkit/item/ItemString.java
  src/main/java/cn/nukkit/nbt/tag/ShortTag.java
  src/main/java/cn/nukkit/utils/ClientChainData.java
  src/main/java/cn/nukkit/utils/LoginChainData.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#286 Release PowerNukkit 1.2.1.0-PN
  CHANGELOG.md
  pom.xml
Labels: Type: bug, Type: enhancement

#302 Fix for item
  src/main/java/cn/nukkit/inventory/PlayerInventory.java
Labels: Resolution: resolved, Type: bug

#308 Add support for Emotes
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/protocol/EmotePacket.java
Labels: Type: enhancement

#310 Update enum sound and particle effect to 1.16
  src/main/java/cn/nukkit/level/ParticleEffect.java
  src/main/java/cn/nukkit/level/Sound.java
Labels: Resolution: resolved, Type: enhancement

#313 Fix dont open inventory
  src/main/java/cn/nukkit/Nukkit.java
Labels: Resolution: resolved, Type: bug
