Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-11, with the labels that each got.

#646 Add a missing potion type (SLOWNESS_IV)
  src/main/java/cn/nukkit/potion/Potion.java
Labels: Status: Awaiting Review, Type: enhancement

#708 Fix Boat problems
  src/main/java/cn/nukkit/entity/item/EntityBoat.java
  src/main/java/cn/nukkit/item/ItemBoat.java
Labels: Status: Awaiting Review, Type: bug, Type: enhancement

#771 Fix: Mobs going into the ground with MobPlugin
  CHANGELOG.md
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Resolution: resolved, Type: compatibility

#772 Fix #770 bamboo and items of blocks with id > 255 not dropping
  CHANGELOG.md
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug

#773 Fix #766 Error saving region files with content over 2 GB
  CHANGELOG.md
  src/main/java/cn/nukkit/level/format/anvil/RegionLoader.java
Labels: Resolution: resolved, Type: bug

#778 Compatibility fix: Unable to change MobPlugin spawner with eggs
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemSpawnEgg.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: compatibility

#779 Fix #777 Falling block falling though scaffolds
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockScaffolding.java
Labels: Type: bug

#780 Fix #776 Grindstone cant remove enchants
  CHANGELOG.md
  src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
Labels: Resolution: resolved, Type: bug

#782 Improves level.dat saving to prevent world corruption
  CHANGELOG.md
  src/main/java/cn/nukkit/level/format/anvil/Anvil.java
  src/main/java/cn/nukkit/level/format/generic/BaseLevelProvider.java
  src/main/java/cn/nukkit/utils/LevelException.java
  src/main/java/cn/nukkit/utils/Utils.java
Labels: Resolution: resolved, Type: enhancement
