Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-09, with the labels that each got.

#543 Merge Cloudburst/master into bleeding
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockBanner.java
  src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/item/EntityFishingHook.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartChest.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartEmpty.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartHopper.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartTNT.java
  src/main/java/cn/nukkit/entity/passive/EntityBee.java
  src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java
  src/main/java/cn/nukkit/item/ItemBanner.java
  src/main/java/cn/nukkit/item/ItemEndCrystal.java
  src/main/java/cn/nukkit/item/ItemHoneyBottle.java
  src/main/java/cn/nukkit/item/ItemHoneycomb.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/food/Food.java
  src/main/java/cn/nukkit/item/food/FoodHoney.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/Sound.java
  src/main/java/cn/nukkit/network/protocol/AdventureSettingsPacket.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
  src/main/java/cn/nukkit/plugin/PluginManager.java
  src/main/java/cn/nukkit/potion/Potion.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#544 Fix a duplication exploit
  src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
  src/test/java/cn/nukkit/PlayerTest.java
  src/test/java/cn/nukkit/ServerTest.java
Labels: Resolution: resolved, Type: bug

#547 Fix: Some Sound Issues Caused By Me
  src/main/java/cn/nukkit/entity/item/EntityFirework.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug

#545 Adds gitpod support
  .gitpod.yml
Labels: Resolution: resolved, Type: Tool

#541 Improves block state error handling
  .idea/codeStyles/Project.xml
  pom.xml
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockFire.java
  src/main/java/cn/nukkit/block/BlockFireSoul.java
  src/main/java/cn/nukkit/block/BlockFlowerPot.java
  src/main/java/cn/nukkit/block/BlockLog.java
  src/main/java/cn/nukkit/block/BlockPistonBase.java
  src/main/java/cn/nukkit/block/BlockSignPost.java
  src/main/java/cn/nukkit/block/BlockSlab.java
  src/main/java/cn/nukkit/block/BlockSnowLayer.java
  src/main/java/cn/nukkit/block/BlockTurtleEgg.java
  src/main/java/cn/nukkit/blockproperty/ArrayBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/BlockProperties.java
  src/main/java/cn/nukkit/blockproperty/BlockProperty.java
  src/main/java/cn/nukkit/blockproperty/BooleanBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/IntBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/UnsignedIntBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/exception/InvalidBlockPropertyException.java
  src/main/java/cn/nukkit/blockproperty/exception/InvalidBlockPropertyMetaException.java
  src/main/java/cn/nukkit/blockproperty/exception/InvalidBlockPropertyValueException.java
  src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/blockstate/BlockStateRepair.java
  src/main/java/cn/nukkit/blockstate/BlockStateRepairCallback.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/IntMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/LongMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/MutableBlockState.java
  src/main/java/cn/nukkit/blockstate/exception/InvalidBlockStateDataTypeException.java
  src/main/java/cn/nukkit/blockstate/exception/InvalidBlockStateException.java
  src/main/java/cn/nukkit/event/HandlerList.java
  src/main/java/cn/nukkit/event/blockstate/BlockStateRepairEvent.java
  src/main/java/cn/nukkit/event/blockstate/BlockStateRepairFinishEvent.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/ChunkSection.java
  src/main/java/cn/nukkit/level/format/FullChunk.java
  src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
  src/main/java/cn/nukkit/level/format/updater/WallUpdater.java
  src/main/java/cn/nukkit/nbt/tag/CompoundTag.java
  src/main/java/cn/nukkit/nbt/tag/StringTag.java
  src/main/java/cn/nukkit/nbt/tag/Tag.java
  src/main/java/cn/nukkit/positiontracking/PositionTrackingStorage.java
  src/main/resources/block_ids.csv
  src/test/java/cn/nukkit/block/BlockLeaves2Test.java
  src/test/java/cn/nukkit/blockproperty/BlockPropertyTest.java
  src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
  src/test/java/cn/nukkit/level/format/generic/BaseChunkTest.java
Labels: Resolution: resolved, Type: bug

#552 Update .gitpod.yml
  .gitpod.yml
Labels: Status: Awaiting Merge, Type: Tool

#557 Fixes errors handling invalid ItemBlock meta
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/entity/EntityHumanType.java
  src/main/java/cn/nukkit/item/ItemBlock.java
  src/main/java/cn/nukkit/level/Level.java
  src/test/java/cn/nukkit/PlayerTest.java
  src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
  src/test/java/cn/nukkit/item/ItemBlockTest.java
  src/test/java/cn/nukkit/test/LogLevelAdjuster.java
  src/test/resources/log4j2.xml
Labels: Resolution: resolved, Type: bug

#560 Fix error sending chunk when it has invalid block states
  src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/Loggers.java
  src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
  src/test/java/cn/nukkit/level/format/anvil/util/BlockStorageTest.java
Labels: Resolution: resolved, Type: bug

#563 Fix grass spread/decay, light props of ice variants; upgrade dirt, podzol, grass, grass_path
  src/main/java/cn/nukkit/block/BlockDirt.java
  src/main/java/cn/nukkit/block/BlockGrass.java
  src/main/java/cn/nukkit/block/BlockIcePacked.java
  src/main/java/cn/nukkit/block/BlockPodzol.java
  src/main/java/cn/nukkit/blockproperty/value/DirtType.java
  src/test/java/cn/nukkit/ServerTest.java
  src/test/java/cn/nukkit/block/BlockGrassTest.java
  src/test/java/cn/nukkit/math/NukkitRandomTest.java
  src/test/java/cn/nukkit/test/answer/AnswerPositionedBlock.java
  src/test/java/cn/nukkit/test/matcher/ExtraArgumentMatchers.java
  src/test/java/cn/nukkit/test/matcher/InRange.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#564 Fix: BlockState not calling callbacks when auto-repairing illegal states
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/blockstate/BlockStateRepairCallback.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/Loggers.java
  src/main/java/cn/nukkit/level/Level.java
  src/test/java/cn/nukkit/level/LevelTest.java
  src/test/java/cn/nukkit/test/LogLevelAdjuster.java
Labels: Resolution: resolved, Type: bug

#555 [Issue #554 Fix] Ice break fix
  CHANGELOG.md
  src/main/java/cn/nukkit/block/BlockIce.java
Labels: Type: bug

#553 Add 1.3.1.5-PN at README.md
  README.md
Labels: Resolution: resolved, Type: Tool

#572 Fix #362 Kelp not consuming bone meal after growing
  src/main/java/cn/nukkit/block/BlockKelp.java
  src/test/java/cn/nukkit/block/BlockKelpTest.java
Labels: Resolution: resolved, Type: bug

#573 Add Sweet Berries to Composter
  src/main/java/cn/nukkit/block/BlockComposter.java
Labels: Resolution: resolved, Type: bug

#579 Implement twisting, weeping vines, improves custom block compatibility
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockComposter.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockMeta.java
  src/main/java/cn/nukkit/block/BlockVinesNether.java
  src/main/java/cn/nukkit/block/BlockVinesTwisting.java
  src/main/java/cn/nukkit/block/BlockVinesWeeping.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/command/data/CommandParameter.java
  src/main/java/cn/nukkit/command/defaults/GiveCommand.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/Position.java
  src/main/java/cn/nukkit/math/Vector3.java
  src/main/java/cn/nukkit/positiontracking/PositionTracking.java
  src/main/java/cn/nukkit/utils/OptionalBoolean.java
  src/main/java/cn/nukkit/utils/functional/BooleanConsumer.java
Labels: Resolution: resolved, Type: enhancement

#568 Fix Not able to use Enchanted Book in Grindstone
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/command/defaults/EnchantCommand.java
  src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
  src/main/java/cn/nukkit/inventory/PlayerUIComponent.java
  src/main/java/cn/nukkit/inventory/transaction/action/CraftingTakeResultExperienceAction.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/math/NukkitMath.java
  src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
  src/test/java/cn/nukkit/inventory/GrindstoneInventoryTest.java
  src/test/java/cn/nukkit/math/NukkitMathTest.java
Labels: Resolution: resolved, Type: bug

#567 Improves compatibility with worldgen plugins
  .idea/codeStyles/Project.xml
  runtime_block_states.dat.dump.txt
  src/main/java/cn/nukkit/api/NewRakNetOnly.java
  src/main/java/cn/nukkit/api/RemovedFromNewRakNet.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockFallableMeta.java
  src/main/java/cn/nukkit/block/BlockGlassPaneStained.java
  src/main/java/cn/nukkit/block/BlockGlassStained.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockKelp.java
  src/main/java/cn/nukkit/block/BlockMeta.java
  src/main/java/cn/nukkit/block/BlockShulkerBox.java
  src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/IntMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/LongMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/MutableBlockState.java
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/biome/impl/beach/ColdBeachBiome.java
  src/main/java/cn/nukkit/level/biome/impl/extremehills/ExtremeHillsMBiome.java
  src/main/java/cn/nukkit/level/biome/impl/extremehills/StoneBeachBiome.java
  src/main/java/cn/nukkit/level/biome/impl/iceplains/IcePlainsSpikesBiome.java
  src/main/java/cn/nukkit/level/biome/impl/mesa/MesaBiome.java
  src/main/java/cn/nukkit/level/biome/impl/mesa/MesaPlateauFBiome.java
  src/main/java/cn/nukkit/level/biome/impl/mushroom/MushroomIslandBiome.java
  src/main/java/cn/nukkit/level/biome/impl/ocean/OceanBiome.java
  src/main/java/cn/nukkit/level/biome/impl/taiga/ColdTaigaBiome.java
  src/main/java/cn/nukkit/level/biome/type/CoveredBiome.java
  src/main/java/cn/nukkit/level/biome/type/GrassyBiome.java
  src/main/java/cn/nukkit/level/biome/type/SandyBiome.java
  src/main/java/cn/nukkit/level/biome/type/SnowyBiome.java
  src/main/java/cn/nukkit/level/biome/type/WateryBiome.java
  src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
  src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorOre.java
  src/main/resources/runtime_block_states_overrides.dat
  src/test/java/cn/nukkit/block/BlockKelpTest.java
  src/test/java/test/OverridesUpdater.java
Labels: Resolution: resolved, Type: compatibility, Type: enhancement

#591 Fix resource leak and makes the enviroment easier to test
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockUnknown.java
  src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IntMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/LongMutableBlockState.java
  src/main/java/cn/nukkit/command/defaults/BanIpCommand.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/level/format/anvil/Anvil.java
  src/main/java/cn/nukkit/level/format/anvil/Chunk.java
  src/main/java/cn/nukkit/level/format/generic/BaseLevelProvider.java
  src/main/java/cn/nukkit/nbt/NBTIO.java
  src/main/java/cn/nukkit/nbt/stream/PGZIPOutputStream.java
  src/main/java/cn/nukkit/network/protocol/LevelEventGenericPacket.java
  src/main/java/cn/nukkit/utils/Binary.java
  src/main/java/cn/nukkit/utils/BinaryStream.java
  src/main/java/cn/nukkit/utils/Zlib.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#594 Improves combat and MobPlugin compatibility
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/EntityHumanType.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
  src/main/java/cn/nukkit/item/ItemBow.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug, Type: compatibility

#601 Fix: Stems not detaching from broken melon/pumpkin and upgrades the stems
  src/main/java/cn/nukkit/block/BlockCrops.java
  src/main/java/cn/nukkit/block/BlockCropsStem.java
  src/main/java/cn/nukkit/block/BlockStemMelon.java
  src/main/java/cn/nukkit/block/BlockStemPumpkin.java
  src/main/java/cn/nukkit/math/BlockFace.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#598 Add missing Interact Button Text
  src/main/java/cn/nukkit/entity/item/EntityBoat.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartEmpty.java
  src/main/java/cn/nukkit/entity/item/EntityVehicle.java
Labels: Resolution: resolved, Type: enhancement

#602 Fix ice behaviour
  src/main/java/cn/nukkit/block/BlockIce.java
Labels: Type: bug

#569 Fix totems issues and correcting
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Resolution: resolved, Type: bug

#608 Add Bed Set Spawn Behavior
  src/main/java/cn/nukkit/block/BlockBed.java
Labels: Resolution: resolved, Type: enhancement

#538 Implement Target Block; Fix the lodestone trackingHandle persistence
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBell.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockTNT.java
  src/main/java/cn/nukkit/block/BlockTarget.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/blockentity/BlockEntityLodestone.java
  src/main/java/cn/nukkit/blockentity/BlockEntityTarget.java
  src/main/java/cn/nukkit/entity/item/EntityFirework.java
  src/main/java/cn/nukkit/entity/projectile/EntityArrow.java
  src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
  src/main/java/cn/nukkit/item/ItemTool.java
  src/main/java/cn/nukkit/level/MovingObjectPosition.java
  src/main/java/cn/nukkit/math/AxisAlignedBB.java
  src/main/java/cn/nukkit/math/BlockVector3.java
  src/main/java/cn/nukkit/math/Vector3.java
  src/main/java/cn/nukkit/math/Vector3f.java
  src/main/java/cn/nukkit/math/VectorMath.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#605 Implements setting to disable safe spawning
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/resources/default-nukkit.yml
Labels: Resolution: resolved, Type: enhancement

#613 Fix bed behavior
  src/main/java/cn/nukkit/block/BlockBed.java
Labels: Resolution: resolved, Type: bug

#617 Random fixes for 1.4.0.0-PN-SNAPSHOT
  .gitattributes
  src/main/java/cn/nukkit/block/BlockBed.java
  src/main/java/cn/nukkit/block/BlockFlowerPot.java
  src/main/java/cn/nukkit/block/BlockFungus.java
  src/main/java/cn/nukkit/block/BlockGrassPath.java
  src/main/java/cn/nukkit/block/BlockLantern.java
  src/main/java/cn/nukkit/block/BlockRedstoneWire.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/item/Item.java
  src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
Labels: Resolution: resolved, Type: bug

#627 Random fixes for 1.4.0.0-PN-SNAPSHOT
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/api/PowerNukkitDifference.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockLantern.java
  src/main/java/cn/nukkit/block/BlockMoving.java
  src/main/java/cn/nukkit/block/BlockUndyedShulkerBox.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/command/defaults/GiveCommand.java
  src/main/java/cn/nukkit/entity/EntityHumanType.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
  src/main/java/cn/nukkit/entity/projectile/EntityArrow.java
  src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
Labels: Resolution: resolved, Type: bug

#629 Fix: Cancelling CraftItemEvent makes you loose the recipe
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockGrindstone.java
  src/main/java/cn/nukkit/inventory/GrindstoneInventory.java
  src/main/java/cn/nukkit/inventory/transaction/CraftingTransaction.java
  src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
  src/main/java/cn/nukkit/network/protocol/CraftingEventPacket.java
Labels: Resolution: resolved, Type: bug

#631 Fix: WallUpdater exception when updating walls with invalid type
  pom.xml
  src/main/java/cn/nukkit/blockproperty/BlockProperty.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/updater/ChunkUpdater.java
  src/main/java/cn/nukkit/level/format/updater/WallUpdater.java
  src/test/java/cn/nukkit/level/format/updater/WallUpdaterTest.java
Labels: Resolution: resolved, Type: bug

#632 Make use of the PowerNukkitExtension to handle the test mocks
  pom.xml
  src/test/java/cn/nukkit/PlayerTest.java
  src/test/java/cn/nukkit/block/BlockEnderChestTest.java
  src/test/java/cn/nukkit/block/BlockGrassTest.java
  src/test/java/cn/nukkit/block/BlockKelpTest.java
  src/test/java/cn/nukkit/block/BlockLeaves2Test.java
  src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
  src/test/java/cn/nukkit/inventory/EnchantInventoryTest.java
  src/test/java/cn/nukkit/inventory/GrindstoneInventoryTest.java
  src/test/java/cn/nukkit/item/ItemBlockTest.java
  src/test/java/cn/nukkit/level/LevelTest.java
  src/test/java/cn/nukkit/level/format/anvil/util/BlockStorageTest.java
  src/test/java/cn/nukkit/level/format/generic/BaseChunkTest.java
  src/test/java/cn/nukkit/level/format/updater/NewLeafUpdaterTest.java
  src/test/java/cn/nukkit/test/NetherUpdateTest.java
  src/test/java/org/powernukkit/tools/BlockIdListGenerator.java
  src/test/java/org/powernukkit/tools/BlockStateReader.java
  src/test/java/org/powernukkit/tools/BlockStates.java
  src/test/java/org/powernukkit/tools/OverridesUpdater.java
  src/test/java/org/powernukkit/tools/RuntimeBlockStateDumper.java
  src/test/java/org/powernukkit/tools/SimpleBlocksReader.java
Labels: Resolution: resolved, Type: Tool

#634 Create method to execute fast block scanning on big areas
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/level/ChunkManager.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/ChunkSection.java
  src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
  src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
  src/main/java/cn/nukkit/level/format/generic/EmptyChunkSection.java
  src/main/java/cn/nukkit/math/BlockVector3.java
  src/main/java/cn/nukkit/math/ChunkVector2.java
  src/main/java/cn/nukkit/math/Vector3.java
Labels: Resolution: resolved, Type: bug, Type: enhancement

#633 Fixes some nether portal issues
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockNetherPortal.java
  src/main/java/cn/nukkit/block/BlockObsidian.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/level/EnumLevel.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
  src/main/java/cn/nukkit/level/format/generic/BaseFullChunk.java
  src/main/java/cn/nukkit/math/Vector2.java
  src/main/java/cn/nukkit/math/Vector3.java
Labels: Status: Awaiting Review, Type: bug

#645 Random fixes
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockLever.java
  src/main/java/cn/nukkit/block/BlockObserver.java
  src/main/java/cn/nukkit/block/BlockRedstoneWire.java
  src/main/java/cn/nukkit/block/BlockSkull.java
  src/main/java/cn/nukkit/blockentity/BlockEntitySkull.java
Labels: Type: bug, Type: enhancement

#651 Fix infinite recursive loop when repairing a block
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug
