Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-07, with the labels that each got.

#320 Fix multiple output crafting.
  src/main/java/cn/nukkit/Player.java
Labels: Resolution: resolved, Type: bug

#324 Fixes incompatibility with the regular version of GAC
  CHANGELOG.md
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
Labels: Type: compatibility

#315 Add new Entitys
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/mob/EntityHoglin.java
  src/main/java/cn/nukkit/entity/mob/EntityPiglin.java
  src/main/java/cn/nukkit/entity/mob/EntityZoglin.java
  src/main/java/cn/nukkit/entity/passive/EntityStrider.java
  src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
Labels: Resolution: resolved, Type: enhancement

#326 Pull commits from NukkitX
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/Nukkit.java
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockEnchantingTable.java
  src/main/java/cn/nukkit/event/inventory/EnchantItemEvent.java
  src/main/java/cn/nukkit/inventory/EnchantInventory.java
  src/main/java/cn/nukkit/inventory/transaction/EnchantTransaction.java
  src/main/java/cn/nukkit/inventory/transaction/action/EnchantingAction.java
  src/main/java/cn/nukkit/network/protocol/InventoryTransactionPacket.java
  src/main/java/cn/nukkit/network/protocol/PlayerEnchantOptionsPacket.java
  src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
Labels: Type: bug, Type: enhancement

#330 Updating README and CHANGELOG
  CHANGELOG.md
  README.md
Labels: Resolution: resolved, Type: enhancement

#348 Update guava from 21.0 to 24.1.1
  pom.xml
Labels: Resolution: resolved, Type: dependencies

#338 Makes Dried Kelp Block can be used as fuel in furnaces
  src/main/java/cn/nukkit/inventory/Fuel.java
Labels: Resolution: resolved, Type: bug

#344 Fixes Piston Bugs (GlobalBlockPalette + sticky piston not pulling other sticky piston)
  src/main/java/cn/nukkit/blockentity/BlockEntityPistonArm.java
  src/main/java/cn/nukkit/level/GlobalBlockPalette.java
Labels: Resolution: resolved, Type: bug

#297 Complete Netherite Implementation
  .github/CODEOWNERS
  block-states.ini
  runtime_block_states.dat.dump.txt
  simple-blocks-nukkit.txt
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockDirt.java
  src/main/java/cn/nukkit/block/BlockGrass.java
  src/main/java/cn/nukkit/block/BlockGrassPath.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockNetherite.java
  src/main/java/cn/nukkit/block/BlockObsidian.java
  src/main/java/cn/nukkit/inventory/AnvilInventory.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemArmor.java
  src/main/java/cn/nukkit/item/ItemAxeNetherite.java
  src/main/java/cn/nukkit/item/ItemBootsNetherite.java
  src/main/java/cn/nukkit/item/ItemChestplateNetherite.java
  src/main/java/cn/nukkit/item/ItemHelmetNetherite.java
  src/main/java/cn/nukkit/item/ItemHoeNetherite.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemIngotNetherite.java
  src/main/java/cn/nukkit/item/ItemLeggingsNetherite.java
  src/main/java/cn/nukkit/item/ItemPickaxeNetherite.java
  src/main/java/cn/nukkit/item/ItemScrapNetherite.java
  src/main/java/cn/nukkit/item/ItemShovelNetherite.java
  src/main/java/cn/nukkit/item/ItemSwordNetherite.java
  src/main/java/cn/nukkit/item/ItemTool.java
  src/main/java/cn/nukkit/level/Sound.java
  src/test/java/cn/nukkit/RuntimeBlockStateDumper.java
  src/test/java/test/OverridesUpdater.java
  src/test/java/test/SimpleBlocksReader.java
Labels: Resolution: resolved, Type: enhancement

#358 Fix regression of a compatibility issue with FAWE (air blocks with meta)
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
Labels: Resolution: resolved, Type: compatibility

#327 [WIP] Crimson/Warped Things Implementation
  runtime_block_states.dat.dump.txt
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockButtonCrimson.java
  src/main/java/cn/nukkit/block/BlockButtonWarped.java
  src/main/java/cn/nukkit/block/BlockCrimsonHyphae.java
  src/main/java/cn/nukkit/block/BlockCrimsonPlanks.java
  src/main/java/cn/nukkit/block/BlockCrimsonSignPost.java
  src/main/java/cn/nukkit/block/BlockCrimsonStem.java
  src/main/java/cn/nukkit/block/BlockCrimsonStrippedHyphae.java
  src/main/java/cn/nukkit/block/BlockCrimsonStrippedStem.java
  src/main/java/cn/nukkit/block/BlockCrimsonWallSign.java
  src/main/java/cn/nukkit/block/BlockDoorCrimson.java
  src/main/java/cn/nukkit/block/BlockDoorWarped.java
  src/main/java/cn/nukkit/block/BlockDoubleSlabCrimson.java
  src/main/java/cn/nukkit/block/BlockDoubleSlabWarped.java
  src/main/java/cn/nukkit/block/BlockFenceCrimson.java
  src/main/java/cn/nukkit/block/BlockFenceGateCrimson.java
  src/main/java/cn/nukkit/block/BlockFenceGateWarped.java
  src/main/java/cn/nukkit/block/BlockFenceWarped.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockPressurePlateCrimson.java
  src/main/java/cn/nukkit/block/BlockPressurePlateWarped.java
  src/main/java/cn/nukkit/block/BlockSlabCrimson.java
  src/main/java/cn/nukkit/block/BlockSlabWarped.java
  src/main/java/cn/nukkit/block/BlockStairsCrimson.java
  src/main/java/cn/nukkit/block/BlockStairsWarped.java
  src/main/java/cn/nukkit/block/BlockTrapdoorCrimson.java
  src/main/java/cn/nukkit/block/BlockTrapdoorWarped.java
  src/main/java/cn/nukkit/block/BlockWarpedHyphae.java
  src/main/java/cn/nukkit/block/BlockWarpedPlanks.java
  src/main/java/cn/nukkit/block/BlockWarpedSignPost.java
  src/main/java/cn/nukkit/block/BlockWarpedStem.java
  src/main/java/cn/nukkit/block/BlockWarpedStrippedHyphae.java
  src/main/java/cn/nukkit/block/BlockWarpedStrippedStem.java
  src/main/java/cn/nukkit/block/BlockWarpedWallSign.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemCrimsonSign.java
  src/main/java/cn/nukkit/item/ItemDoorCrimson.java
  src/main/java/cn/nukkit/item/ItemDoorWarped.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemWarpedSign.java
Labels: Resolution: resolved, Type: enhancement

#369 Allow resource packs to have sub-folder inside itself
  src/main/java/cn/nukkit/resourcepacks/ResourcePackManager.java
  src/main/java/cn/nukkit/resourcepacks/ZippedResourcePack.java
Labels: Resolution: resolved, Type: compatibility

#371 Adding our website and forum
  CHANGELOG.md
  README.md
Labels: Resolution: resolved, Type: enhancement

#384 Fixes crafting recipes and pulls changes from upstream
  src/main/java/cn/nukkit/inventory/PlayerUIInventory.java
  src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
  src/main/java/cn/nukkit/item/Item.java
Labels: Type: bug

#374 Pigstep Record implementation
  src/main/java/cn/nukkit/blockentity/BlockEntityJukebox.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemRecordPigstep.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
Labels: Status: Awaiting Merge, Type: enhancement

#373 Warped Fungus on a Stick implementation
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/java/cn/nukkit/item/ItemWarpedFungusOnAStick.java
Labels: Resolution: resolved, Type: enhancement

#377 Fishing rods will not be damaged when breaking blocks/attacking entities
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemFishingRod.java
  src/main/java/cn/nukkit/item/ItemTool.java
  src/main/java/cn/nukkit/item/ItemWarpedFungusOnAStick.java
Labels: Resolution: resolved, Type: bug

#287 Implement all fixes
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockCocoa.java
  src/main/java/cn/nukkit/block/BlockGrindstone.java
  src/main/java/cn/nukkit/block/BlockLantern.java
  src/main/java/cn/nukkit/block/BlockLiquid.java
  src/main/java/cn/nukkit/block/BlockSeaPickle.java
  src/main/java/cn/nukkit/command/defaults/TeleportCommand.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/biome/impl/mesa/MesaBiome.java
Labels: Resolution: resolved, Type: bug

#351 Shield implement
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
  src/main/java/cn/nukkit/entity/EntityHumanType.java
  src/main/java/cn/nukkit/entity/EntityLiving.java
  src/main/java/cn/nukkit/event/entity/EntityDamageBlockedEvent.java
  src/main/java/cn/nukkit/item/ItemShield.java
  src/main/java/cn/nukkit/item/ItemTool.java
  src/main/java/cn/nukkit/utils/Utils.java
Labels: Resolution: resolved, Type: enhancement

#359 Fixes Pistons again
  src/main/java/cn/nukkit/block/BlockPistonBase.java
Labels: Resolution: resolved, Type: bug

#361 Fixes #360 Wrong Bamboo Behaviors
  src/main/java/cn/nukkit/block/BlockBamboo.java
  src/main/java/cn/nukkit/block/BlockBambooSapling.java
  src/main/java/cn/nukkit/level/Level.java
Labels: Resolution: resolved, Type: bug

#378 Implement ArmorStand
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockBamboo.java
  src/main/java/cn/nukkit/block/BlockBambooSapling.java
  src/main/java/cn/nukkit/block/BlockConduit.java
  src/main/java/cn/nukkit/block/BlockFlowerPot.java
  src/main/java/cn/nukkit/block/BlockTurtleEgg.java
  src/main/java/cn/nukkit/entity/item/EntityArmorStand.java
  src/main/java/cn/nukkit/inventory/EntityArmorInventory.java
  src/main/java/cn/nukkit/inventory/EntityEquipmentInventory.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemArmorStand.java
Labels: Resolution: resolved, Type: enhancement

#388 Fixes old doors rendering incorrectly at client
  runtime_block_states.dat.dump.txt
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/resources/runtime_block_states_overrides.dat
  src/test/java/test/OverridesUpdater.java
Labels: Resolution: resolved, Type: bug

#317 Soul Lantern, Soul Torch, Chain Implementation
  runtime_block_states.dat.dump.txt
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBell.java
  src/main/java/cn/nukkit/block/BlockChain.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockLantern.java
  src/main/java/cn/nukkit/block/BlockSoulLantern.java
  src/main/java/cn/nukkit/block/BlockSoulTorch.java
  src/main/java/cn/nukkit/block/BlockTorch.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemChain.java
  src/main/java/cn/nukkit/item/ItemID.java
  src/main/resources/runtime_block_states_overrides.dat
  src/test/java/test/OverridesUpdater.java
Labels: Resolution: resolved, Type: enhancement

#391 Fix crash caused by a missing pre-calculation on trapdoors
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
Labels: Resolution: resolved, Type: bug

#395 Implements Basalt and Polished Basalt
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBasalt.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockLava.java
  src/main/java/cn/nukkit/block/BlockPolishedBasalt.java
Labels: Resolution: resolved, Type: enhancement

#396 Fixes torch placement issues
  src/main/java/cn/nukkit/block/BlockTorch.java
Labels: Resolution: resolved, Type: bug
