Repository PowerNukkit/PowerNukkit, pull requests merged in 2020-10, with the labels that each got.

#665 Fix: Nether Sprout, Crimson/Warped Roots not showing
  src/main/java/cn/nukkit/block/BlockRoots.java
Labels: Resolution: resolved, Type: bug

#635 Add more bed behavior
  src/main/java/cn/nukkit/block/BlockBed.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/mob/EntityBlaze.java
  src/main/java/cn/nukkit/entity/mob/EntityCaveSpider.java
  src/main/java/cn/nukkit/entity/mob/EntityCreeper.java
  src/main/java/cn/nukkit/entity/mob/EntityDrowned.java
  src/main/java/cn/nukkit/entity/mob/EntityElderGuardian.java
  src/main/java/cn/nukkit/entity/mob/EntityEnderman.java
  src/main/java/cn/nukkit/entity/mob/EntityEndermite.java
  src/main/java/cn/nukkit/entity/mob/EntityEvoker.java
  src/main/java/cn/nukkit/entity/mob/EntityGuardian.java
  src/main/java/cn/nukkit/entity/mob/EntityHusk.java
  src/main/java/cn/nukkit/entity/mob/EntityPhantom.java
  src/main/java/cn/nukkit/entity/mob/EntityPiglin.java
  src/main/java/cn/nukkit/entity/mob/EntityPiglinBrute.java
  src/main/java/cn/nukkit/entity/mob/EntityPillager.java
  src/main/java/cn/nukkit/entity/mob/EntityRavager.java
  src/main/java/cn/nukkit/entity/mob/EntitySilverfish.java
  src/main/java/cn/nukkit/entity/mob/EntitySkeleton.java
  src/main/java/cn/nukkit/entity/mob/EntitySpider.java
  src/main/java/cn/nukkit/entity/mob/EntityStray.java
  src/main/java/cn/nukkit/entity/mob/EntityVex.java
  src/main/java/cn/nukkit/entity/mob/EntityVindicator.java
  src/main/java/cn/nukkit/entity/mob/EntityWitch.java
  src/main/java/cn/nukkit/entity/mob/EntityWither.java
  src/main/java/cn/nukkit/entity/mob/EntityWitherSkeleton.java
  src/main/java/cn/nukkit/entity/mob/EntityZoglin.java
  src/main/java/cn/nukkit/entity/mob/EntityZombie.java
  src/main/java/cn/nukkit/entity/mob/EntityZombiePigman.java
  src/main/java/cn/nukkit/entity/mob/EntityZombieVillager.java
Labels: Resolution: resolved, Type: enhancement

#653 Zoglin is undead
  src/main/java/cn/nukkit/entity/mob/EntityZoglin.java
Labels: Resolution: resolved, Type: bug

#647 Add option that set players skin trusted
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/resources/default-nukkit.yml
Labels: Resolution: resolved, Type: enhancement

#674 Fix netherite tools and adds a convenience method
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/item/Item.java
Labels: Type: bug

#678 Fix: UnsupportedOperation: This BlockStorage is immutable
  src/main/java/cn/nukkit/level/format/anvil/SingleLayerStorage.java
Labels: Type: bug

#679 Fix: LayerStorage.size() and create some unit tests
  src/main/java/cn/nukkit/level/format/anvil/MultiLayerStorage.java
  src/main/java/cn/nukkit/level/format/anvil/SingleLayerStorage.java
  src/test/java/cn/nukkit/level/format/anvil/MultiLayerStorageTest.java
  src/test/java/cn/nukkit/level/format/anvil/SingleLayerStorageTest.java
Labels: Resolution: resolved, Type: bug

#673 Added curse enchantments
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/inventory/transaction/InventoryTransaction.java
Labels: Status: Awaiting Merge, Type: enhancement

#685 Fixes reduntant sendWeather call being sent to client.
  src/main/java/cn/nukkit/Player.java
Labels: Resolution: resolved, Type: bug

#684 Fixes all blocks having lava resistance and non-netherite items not burning
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/item/EntityItem.java
Labels: Resolution: resolved, Type: bug

#688 Fix: Property facing_direction not found while ticking entity hopper
  src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
Labels: Status: Awaiting Review, Type: bug

#689 Adds generic method to check if an entity collides with any given block type.
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Status: Awaiting Review, Type: enhancement

#682 Adds the Soul Speed Enchantment
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockSoulSand.java
  src/main/java/cn/nukkit/block/BlockSoulSoil.java
  src/main/java/cn/nukkit/item/enchantment/Enchantment.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentSoulSpeed.java
Labels: Resolution: resolved, Type: enhancement

#695 Add new option that enable or disable checkMovement
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/resources/default-nukkit.yml
Labels: Resolution: resolved, Type: enhancement

#693 Add TimeSinceRest to Player
  src/main/java/cn/nukkit/Player.java
Labels: Resolution: resolved, Type: enhancement

#663 Update Pumpkin
  src/main/java/cn/nukkit/block/BlockCarvedPumpkin.java
  src/main/java/cn/nukkit/block/BlockPumpkin.java
  src/main/java/cn/nukkit/block/BlockPumpkinLit.java
Labels: Status: In Progress, Type: enhancement

#703 lily pads now can be placed above water
  src/main/java/cn/nukkit/block/BlockWaterLily.java
Labels: Status: Awaiting Review, Type: enhancement

#698 Fix: ChunkSection.allocateBlob() IndexOutOfBoundsException: Index: 3, Size: 3
  .idea/codeStyles/Project.xml
  src/main/java/cn/nukkit/api/Unsigned.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockDoor.java
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
  src/main/java/cn/nukkit/blockstate/BigIntegerMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/ByteMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/IntMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/LongMutableBlockState.java
  src/main/java/cn/nukkit/blockstate/MutableBlockState.java
  src/main/java/cn/nukkit/blockstate/ZeroMutableBlockState.java
  src/main/java/cn/nukkit/level/format/anvil/ChunkSection.java
  src/main/java/cn/nukkit/level/format/anvil/LayerStorage.java
  src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
  src/main/java/cn/nukkit/utils/Validation.java
  src/test/java/cn/nukkit/level/format/anvil/ChunkSectionTest.java
Labels: Resolution: resolved, Type: bug

#722 Fix: Blocks disappearing when building up
  src/main/java/cn/nukkit/level/Level.java
  src/test/java/cn/nukkit/block/BlockEnderChestTest.java
Labels: Resolution: resolved, Type: bug

#725 Fix Cake
  src/main/java/cn/nukkit/block/BlockCake.java
  src/main/java/cn/nukkit/item/ItemCake.java
Labels: Type: bug
