Repository PowerNukkit/PowerNukkit, pull requests merged in 2021-01, with the labels that each got.

#880 Fix nether portal replace by right-clicking with lava or water bucket and dispensers now can destroy nether portals
  src/main/java/cn/nukkit/block/BlockNetherPortal.java
  src/main/java/cn/nukkit/dispenser/BucketDispenseBehavior.java
Labels: Implementation: Block, Implementation: BlockEntity, size/XS

#882 [v1.3.x] Pull changes from upstream
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/network/CompressBatchedTask.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/network/protocol/DataPacket.java
  src/main/java/cn/nukkit/network/protocol/PlayerListPacket.java
  src/test/java/cn/nukkit/test/NetherUpdateTest.java
  src/test/resources/cn/nukkit/test/NetherUpdateTest.smallPacket.dump.txt
  src/test/resources/cn/nukkit/test/NetherUpdateTest.vanillaPacket.dump.txt
Labels: Resolution: resolved, Type: merge

#883 [v1.4.0] Pull changes from v1.3.X
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/network/CompressBatchedTask.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/network/protocol/DataPacket.java
  src/main/java/cn/nukkit/network/protocol/PlayerListPacket.java
  src/test/java/cn/nukkit/test/NetherUpdateTest.java
  src/test/resources/cn/nukkit/test/NetherUpdateTest.smallPacket.dump.txt
  src/test/resources/cn/nukkit/test/NetherUpdateTest.vanillaPacket.dump.txt
Labels: Resolution: resolved, Type: merge

#885 Fix for missing effect particles after re-login
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Resolution: resolved, Type: bug, size/XS

#756 Add more TextPacket related methods to Player
  src/main/java/cn/nukkit/Player.java
Labels: Resolution: resolved, Type: enhancement, size/XS

#832 Add Emerald Ore Populator to Extreme Hills Biomes
  src/main/java/cn/nukkit/level/biome/impl/extremehills/ExtremeHillsBiome.java
  src/main/java/cn/nukkit/level/generator/populator/impl/PopulatorOreEmerald.java
Labels: Resolution: resolved, Tag: Generation, size/S

#893 Fix for missing effect particles after re-login
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Resolution: resolved, Type: enhancement, size/XS

#890 Fix speed effect does not work properly while sprinting
  src/main/java/cn/nukkit/Player.java
Labels: Status: Awaiting Review, Type: enhancement, size/XS

#872 Implement all Trident enchantment and improve a lot of Trident related things
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/projectile/EntityProjectile.java
  src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java
  src/main/java/cn/nukkit/event/player/PlayerToggleSpinAttackEvent.java
  src/main/java/cn/nukkit/item/ItemTrident.java
Labels: Implementation: Item, Status: Awaiting Review, Tag: Enchantment, size/M

#894 Fixes for beacon
  src/main/java/cn/nukkit/blockentity/BlockEntityBeacon.java
Labels: Status: Awaiting Review, Type: enhancement, size/XS

#750 Redstone fixes + BlockEntity issues fixed
  src/main/java/cn/nukkit/api/DeprecationDetails.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBell.java
  src/main/java/cn/nukkit/block/BlockButton.java
  src/main/java/cn/nukkit/block/BlockDaylightDetector.java
  src/main/java/cn/nukkit/block/BlockDispenser.java
  src/main/java/cn/nukkit/block/BlockDoor.java
  src/main/java/cn/nukkit/block/BlockDropper.java
  src/main/java/cn/nukkit/block/BlockFenceGate.java
  src/main/java/cn/nukkit/block/BlockHopper.java
  src/main/java/cn/nukkit/block/BlockLectern.java
  src/main/java/cn/nukkit/block/BlockLever.java
  src/main/java/cn/nukkit/block/BlockNoteblock.java
  src/main/java/cn/nukkit/block/BlockObserver.java
  src/main/java/cn/nukkit/block/BlockPistonBase.java
  src/main/java/cn/nukkit/block/BlockPistonHead.java
  src/main/java/cn/nukkit/block/BlockPressurePlateBase.java
  src/main/java/cn/nukkit/block/BlockRailActivator.java
  src/main/java/cn/nukkit/block/BlockRailPowered.java
  src/main/java/cn/nukkit/block/BlockRedstone.java
  src/main/java/cn/nukkit/block/BlockRedstoneComparator.java
  src/main/java/cn/nukkit/block/BlockRedstoneDiode.java
  src/main/java/cn/nukkit/block/BlockRedstoneLamp.java
  src/main/java/cn/nukkit/block/BlockRedstoneLampLit.java
  src/main/java/cn/nukkit/block/BlockRedstoneRepeater.java
  src/main/java/cn/nukkit/block/BlockRedstoneTorch.java
  src/main/java/cn/nukkit/block/BlockRedstoneTorchUnlit.java
  src/main/java/cn/nukkit/block/BlockRedstoneWire.java
  src/main/java/cn/nukkit/block/BlockSkull.java
  src/main/java/cn/nukkit/block/BlockTNT.java
  src/main/java/cn/nukkit/block/BlockTarget.java
  src/main/java/cn/nukkit/block/BlockTrapdoor.java
  src/main/java/cn/nukkit/block/BlockTripWire.java
  src/main/java/cn/nukkit/block/BlockTripWireHook.java
  src/main/java/cn/nukkit/blockentity/BlockEntityHopper.java
  src/main/java/cn/nukkit/blockentity/BlockEntityLectern.java
  src/main/java/cn/nukkit/blockentity/BlockEntityPistonArm.java
  src/main/java/cn/nukkit/dispenser/DropperDispenseBehavior.java
  src/main/java/cn/nukkit/dispenser/FlintAndSteelDispenseBehavior.java
  src/main/java/cn/nukkit/dispenser/ProjectileDispenseBehavior.java
  src/main/java/cn/nukkit/entity/item/EntityPrimedTNT.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/utils/RedstoneComponent.java
Labels: Resolution: resolved, Tag: Redstone, Type: bug, Type: enhancement, help wanted, size/XXL

#822 Adds FilterTextPacket to ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
Labels: Resolution: resolved, size/XS

#902 [v1.3.x] Pull changes from upstream
  CHANGELOG.md
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockConcretePowder.java
  src/main/java/cn/nukkit/block/BlockNetherPortal.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/inventory/PlayerInventory.java
  src/main/java/cn/nukkit/inventory/PlayerOffhandInventory.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/network/protocol/DataPacket.java
Labels: Resolution: resolved, Type: merge

#903 [v1.4.0] Pull changes from upstream
  CHANGELOG.md
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/BlockConcretePowder.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/inventory/PlayerInventory.java
  src/main/java/cn/nukkit/inventory/PlayerOffhandInventory.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/network/protocol/DataPacket.java
Labels: Resolution: resolved, Type: merge

#909 Implements API to get the BlockState by runtime id
  src/main/java/cn/nukkit/blockproperty/ArrayBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/BlockProperties.java
  src/main/java/cn/nukkit/blockproperty/BlockProperty.java
  src/main/java/cn/nukkit/blockproperty/BooleanBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/IntBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/UnsignedIntBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/exception/InvalidBlockPropertyPersistenceValueException.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
Labels: Status: Awaiting Review, Status: Needs Testing, Type: enhancement

#911 Fix the path block won't decay to dirt when you place a solid block above it (Fix #904)
  src/main/java/cn/nukkit/block/BlockGrass.java
  src/main/java/cn/nukkit/block/BlockGrassPath.java
Labels: Resolution: resolved, Type: bug

#917 Adds automatic bug reports using Sentry
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/Nukkit.java
  src/main/java/cn/nukkit/Server.java
  src/main/resources/log4j2.xml
Labels: Type: enhancement

#889 Fix packet encoding issue
  src/main/java/cn/nukkit/network/RakNetInterface.java
Labels: Resolution: resolved, Type: bug, size/XS

#920 Improves error logging
  .github/FUNDING.yml
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockPistonBase.java
  src/main/java/cn/nukkit/blockentity/BlockEntity.java
  src/main/java/cn/nukkit/command/ConsoleCommandSender.java
  src/main/java/cn/nukkit/command/FormattedCommandAlias.java
  src/main/java/cn/nukkit/command/SimpleCommandMap.java
  src/main/java/cn/nukkit/command/defaults/DebugPasteCommand.java
  src/main/java/cn/nukkit/command/simple/SimpleCommand.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemMap.java
  src/main/java/cn/nukkit/item/RuntimeItems.java
  src/main/java/cn/nukkit/lang/BaseLang.java
  src/main/java/cn/nukkit/lang/TextContainer.java
  src/main/java/cn/nukkit/level/EnumLevel.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/LevelProviderManager.java
  src/main/java/cn/nukkit/level/format/anvil/Chunk.java
  src/main/java/cn/nukkit/level/format/anvil/RegionLoader.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
  src/main/java/cn/nukkit/level/format/leveldb/Chunk.java
  src/main/java/cn/nukkit/level/format/mcregion/RegionLoader.java
  src/main/java/cn/nukkit/level/generator/Flat.java
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/network/protocol/types/NetworkInventoryAction.java
  src/main/java/cn/nukkit/network/query/QueryHandler.java
  src/main/java/cn/nukkit/network/rcon/RCON.java
  src/main/java/cn/nukkit/network/rcon/RCONServer.java
  src/main/java/cn/nukkit/permission/BanEntry.java
  src/main/java/cn/nukkit/permission/BanList.java
  src/main/java/cn/nukkit/plugin/JavaPluginLoader.java
  src/main/java/cn/nukkit/plugin/MethodEventExecutor.java
  src/main/java/cn/nukkit/plugin/PluginBase.java
  src/main/java/cn/nukkit/plugin/PluginLogger.java
  src/main/java/cn/nukkit/plugin/PluginManager.java
  src/main/java/cn/nukkit/resourcepacks/ResourcePackManager.java
  src/main/java/cn/nukkit/resourcepacks/ZippedResourcePack.java
  src/main/java/cn/nukkit/scheduler/AsyncPool.java
  src/main/java/cn/nukkit/scheduler/AsyncTask.java
  src/main/java/cn/nukkit/scheduler/FileWriteTask.java
  src/main/java/cn/nukkit/scheduler/ServerScheduler.java
  src/main/java/cn/nukkit/scheduler/Task.java
  src/main/java/cn/nukkit/scheduler/TaskHandler.java
  src/main/java/cn/nukkit/utils/Config.java
  src/main/java/cn/nukkit/utils/SimpleConfig.java
  src/main/java/cn/nukkit/utils/Watchdog.java
  src/main/java/cn/nukkit/utils/Zlib.java
  src/main/java/cn/nukkit/utils/bugreport/BugReportGenerator.java
  src/main/java/co/aikar/timings/Timings.java
  src/main/java/co/aikar/timings/TimingsExport.java
  src/test/java/cn/nukkit/PlayerTest.java
Labels: Type: enhancement

#923 Merge nukkitx
  .gitignore
  Dockerfile.arm64
  Makefile
  README.md
  charts/nukkit/.helmignore
  charts/nukkit/Chart.yaml
  charts/nukkit/templates/NOTES.txt
  charts/nukkit/templates/_helpers.tpl
  charts/nukkit/templates/configmap.yaml
  charts/nukkit/templates/deployment.yaml
  charts/nukkit/templates/hpa.yaml
  charts/nukkit/templates/service.yaml
  charts/nukkit/templates/serviceaccount.yaml
  charts/nukkit/templates/tests/test-connection.yaml
  charts/nukkit/values.yaml
  nukkit.yml.default
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockVine.java
  src/main/java/cn/nukkit/event/player/PlayerAsyncPreLoginEvent.java
  src/main/java/cn/nukkit/potion/Effect.java
Labels: Type: merge
