Repository PowerNukkit/PowerNukkit, pull requests merged in 2021-06, with the labels that each got.

#967 Fix dry sponge delete waterlogged block & Fix dry sponge can't absorb water at layer 1
  src/main/java/cn/nukkit/block/BlockSponge.java
Labels: Implementation: Block, Status: Awaiting Review, Type: bug, size/XS

#1115 Implement TickSyncPacket
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/network/protocol/TickSyncPacket.java
Labels: Resolution: resolved, Tag : RakNet, Type: enhancement

#1119 Register TickSyncPacket properly
  src/main/java/cn/nukkit/network/Network.java
Labels: Type: bug

#1132 Dismount entities before teleporting
  src/main/java/cn/nukkit/entity/Entity.java
Labels: Implementation: Entity, Resolution: resolved, Type: bug, size/XS

#1131 Fix backward compatibility with plugins setting full bark logs with 17:13
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockWood.java
  src/main/java/cn/nukkit/block/BlockWoodBark.java
  src/main/java/cn/nukkit/block/BlockWoodStripped.java
  src/main/java/cn/nukkit/blockstate/BlockStateRegistry.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
  src/test/java/cn/nukkit/blockstate/IBlockStateTest.java
Labels: Implementation: Block, Resolution: resolved, Type: compatibility, size/S

#1107 Update guava to 30.1.1 and SnakeYAML to 1.28
  pom.xml
Labels: Resolution: resolved, Type: dependencies, size/XS

#1100 Fixed an abrupt change of day and night
  src/main/java/cn/nukkit/level/Level.java
Labels: Status: Awaiting Review, Type: bug, size/XS

#1103 Fix enchant command
  src/main/java/cn/nukkit/command/defaults/EnchantCommand.java
Labels: Resolution: resolved, Type: bug, size/XS

#702 Arrow being extinguished when in rain
  src/main/java/cn/nukkit/entity/projectile/EntityArrow.java
Labels: Status: Awaiting Review, Type: enhancement, size/XS

#1139 Fixes backward compatibility with generators.
  src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
  src/main/java/cn/nukkit/level/format/generic/BaseChunk.java
  src/test/java/cn/nukkit/level/format/generic/BaseChunkTest.java
Labels: Resolution: resolved, Type: compatibility

#1135 Fix burning mobs and isOnFire() method
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/event/entity/EntityDamageEvent.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/enchantment/Enchantment.java
  src/main/java/cn/nukkit/item/enchantment/EnchantmentFireAspect.java
  src/main/java/cn/nukkit/item/enchantment/sideeffect/SideEffect.java
  src/main/java/cn/nukkit/item/enchantment/sideeffect/SideEffectCombust.java
Labels: Type: bug

#1141 Add Tuff Block
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockTuff.java
Labels: Implementation: Block, Status: Awaiting Review, Type: enhancement, size/XS

#979 Fix Player.sendPosition onGround value
  src/main/java/cn/nukkit/Player.java
Labels: Resolution: resolved, Type: bug, size/XS

#576 Implement the physique of the minecraft swim
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
Labels: Resolution: resolved, Type: bug, size/S

#1146 Implements AnimateEntityPacket
  src/main/java/cn/nukkit/network/Network.java
  src/main/java/cn/nukkit/network/protocol/AnimateEntityPacket.java
Labels: Status: In Progress, Type: enhancement

#1147 Wrong calculation of additional damage for sharpness enchantments
  src/main/java/cn/nukkit/item/enchantment/damage/EnchantmentDamageAll.java
Labels: Implementation: Item, Resolution: resolved, Type: bug, size/XS

#1150 Register missing game rules & entity network IDs + bump API version
  src/main/java/cn/nukkit/Nukkit.java
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/command/defaults/GameruleCommand.java
  src/main/java/cn/nukkit/item/ItemRedstone.java
  src/main/java/cn/nukkit/level/GameRule.java
  src/main/java/cn/nukkit/level/GameRules.java
  src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
  src/main/java/cn/nukkit/utils/BinaryStream.java
  src/main/resources/runtime_item_ids.json
Labels: Resolution: resolved, Tag: Upstream, Type: merge

#1151 Improves /setworldspawn auto-completion
  src/main/java/cn/nukkit/command/defaults/SetWorldSpawnCommand.java
Labels: Resolution: resolved, Type: enhancement, size/XS

#783 Fix and update campfire and soul campfire
  src/main/java/cn/nukkit/block/BlockCampfire.java
  src/main/java/cn/nukkit/block/BlockCampfireSoul.java
  src/main/java/cn/nukkit/entity/item/EntityPotion.java
Labels: Implementation: Block, Resolution: resolved, Type: enhancement, size/M

#1170 Cobwebs are now breakable by using shears
  src/main/java/cn/nukkit/block/Block.java
Labels: Resolution: resolved, Type: bug, size/XS

#1158 Remove duplicated import of ItemFireCharge
  src/main/java/cn/nukkit/item/ItemFireCharge.java
Labels: Status: Awaiting Merge, Type: enhancement, size/XS
