Repository PowerNukkit/PowerNukkit, pull requests merged in 2021-12, with the labels that each got.

#1258 Fixes recipes and item runtime IDs for Minecraft BE 1.18.0
  .github/workflows/sonar.yml
  UPGRADING_TO_NEXT_MINECRAFT.md
  dumps/r12_to_current_block_map.bin
  dumps/r12_to_current_block_map.bin.txt
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
  src/main/resources/biome_definitions.dat
  src/main/resources/creativeitems.json
  src/main/resources/entity_identifiers.dat
  src/main/resources/recipes.json
  src/main/resources/runtime_item_ids.json
  src/test/java/org/powernukkit/updater/AllResourcesDownloader.java
  src/test/java/org/powernukkit/updater/RuntimeItemIdUpdater.java
  src/test/resources/org/powernukkit/updater/dumps/pmmp/required_item_list.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/creativeitems.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/recipes.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/runtime_item_states.json
Labels: Type: enhancement, Resolution: resolved, Tag : Minecraft Version Update, size/S, priority:0

#1266 Bump log4j to 2.15.0
  pom.xml
Labels: Status: In Progress, Type: dependencies, size/XS, priority:0

#1270 Bump log4j to 2.17.0
  pom.xml
Labels: Resolution: resolved, Status: Awaiting Review, Type: dependencies, priority:0
