Repository PowerNukkit/PowerNukkit, pull requests merged in 2021-02, with the labels that each got.

#952 [v1.3] Pull changes from Nukkit
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
  src/main/java/cn/nukkit/entity/item/EntityBoat.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
  src/main/java/cn/nukkit/entity/item/EntityPainting.java
  src/main/java/cn/nukkit/entity/projectile/EntityThrownTrident.java
  src/main/java/cn/nukkit/item/ItemBoat.java
  src/main/java/cn/nukkit/item/ItemBow.java
  src/main/java/cn/nukkit/item/ItemEdible.java
  src/main/java/cn/nukkit/item/ItemEndCrystal.java
  src/main/java/cn/nukkit/item/ItemFireCharge.java
  src/main/java/cn/nukkit/item/ItemFirework.java
  src/main/java/cn/nukkit/item/ItemFlintSteel.java
  src/main/java/cn/nukkit/item/ItemMinecart.java
  src/main/java/cn/nukkit/item/ItemMinecartChest.java
  src/main/java/cn/nukkit/item/ItemMinecartHopper.java
  src/main/java/cn/nukkit/item/ItemMinecartTNT.java
  src/main/java/cn/nukkit/item/ItemPainting.java
  src/main/java/cn/nukkit/item/ItemPotion.java
  src/main/java/cn/nukkit/item/ItemSpawnEgg.java
  src/main/java/cn/nukkit/metrics/Metrics.java
  src/main/java/cn/nukkit/metrics/NukkitMetrics.java
  src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java
Labels: Resolution: resolved, Type: merge

#953 [v1.4] Pull changes from Nukkit
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/entity/EntityHuman.java
  src/main/java/cn/nukkit/entity/item/EntityBoat.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartAbstract.java
  src/main/java/cn/nukkit/entity/item/EntityPainting.java
  src/main/java/cn/nukkit/item/ItemBow.java
  src/main/java/cn/nukkit/item/ItemEdible.java
  src/main/java/cn/nukkit/item/ItemEndCrystal.java
  src/main/java/cn/nukkit/item/ItemFireCharge.java
  src/main/java/cn/nukkit/item/ItemFirework.java
  src/main/java/cn/nukkit/item/ItemFlintSteel.java
  src/main/java/cn/nukkit/item/ItemMinecart.java
  src/main/java/cn/nukkit/item/ItemMinecartChest.java
  src/main/java/cn/nukkit/item/ItemMinecartHopper.java
  src/main/java/cn/nukkit/item/ItemMinecartTNT.java
  src/main/java/cn/nukkit/item/ItemPainting.java
  src/main/java/cn/nukkit/item/ItemPotion.java
  src/main/java/cn/nukkit/item/ItemSpawnEgg.java
  src/main/java/cn/nukkit/metrics/Metrics.java
  src/main/java/cn/nukkit/metrics/NukkitMetrics.java
  src/main/java/cn/nukkit/network/protocol/ResourcePacksInfoPacket.java
Labels: Resolution: resolved, Type: merge

#914 Adds Iron Golem
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/entity/mob/EntityIronGolem.java
Labels: Implementation: Entity, Resolution: resolved, Type: enhancement, size/S

#940 Fix disconnect problems
  src/main/java/cn/nukkit/network/RakNetInterface.java
Labels: Resolution: resolved, Tag : RakNet, Type: bug, Type: compatibility, help wanted, size/XS

#941 Implement Trident Enchantment Impaling
  src/main/java/cn/nukkit/item/enchantment/trident/EnchantmentTridentImpaling.java
Labels: Implementation: Item, Resolution: resolved, Tag: Enchantment, Type: bug, size/XS

#959 Fixes issues with Item.fromString the ordering of items in creative tabs
  CHANGELOG.md
  src/main/java/cn/nukkit/command/defaults/GiveCommand.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/utils/BinaryStream.java
  src/main/resources/creativeitems.json
  src/main/resources/runtime_item_ids.json
Labels: Implementation: Item, Resolution: resolved, Tag : RakNet, Type: bug, size/M

#962 Fixes Unknown item mapping Item Unknown (879:3)
  CHANGELOG.md
  src/main/java/cn/nukkit/nbt/NBTIO.java
  src/test/java/cn/nukkit/nbt/NBTIOTest.java
Labels: Implementation: Item, Resolution: resolved, Type: bug, size/XS

#697 Block Property system upgrades and some fixes along the way
  src/main/java/cn/nukkit/block/BlockAnvil.java
  src/main/java/cn/nukkit/block/BlockBanner.java
  src/main/java/cn/nukkit/block/BlockBedrock.java
  src/main/java/cn/nukkit/block/BlockBeetroot.java
  src/main/java/cn/nukkit/block/BlockBell.java
  src/main/java/cn/nukkit/block/BlockCarrot.java
  src/main/java/cn/nukkit/block/BlockCrops.java
  src/main/java/cn/nukkit/block/BlockCropsStem.java
  src/main/java/cn/nukkit/block/BlockDandelion.java
  src/main/java/cn/nukkit/block/BlockFire.java
  src/main/java/cn/nukkit/block/BlockFlower.java
  src/main/java/cn/nukkit/block/BlockPotato.java
  src/main/java/cn/nukkit/block/BlockRail.java
  src/main/java/cn/nukkit/block/BlockRailActivator.java
  src/main/java/cn/nukkit/block/BlockRailDetector.java
  src/main/java/cn/nukkit/block/BlockRailPowered.java
  src/main/java/cn/nukkit/block/BlockSapling.java
  src/main/java/cn/nukkit/block/BlockSignPost.java
  src/main/java/cn/nukkit/block/BlockWallBanner.java
  src/main/java/cn/nukkit/block/BlockWallBase.java
  src/main/java/cn/nukkit/block/BlockWallSign.java
  src/main/java/cn/nukkit/block/BlockWheat.java
  src/main/java/cn/nukkit/block/BlockWitherRose.java
  src/main/java/cn/nukkit/blockproperty/ArrayBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/BlockProperties.java
  src/main/java/cn/nukkit/blockproperty/BlockProperty.java
  src/main/java/cn/nukkit/blockproperty/BooleanBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/IntBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/UnsignedIntBlockProperty.java
  src/main/java/cn/nukkit/blockproperty/value/AnvilDamage.java
  src/main/java/cn/nukkit/blockproperty/value/BellAttachmentType.java
  src/main/java/cn/nukkit/blockproperty/value/SmallFlowerType.java
  src/main/java/cn/nukkit/blockproperty/value/WoodType.java
  src/main/java/cn/nukkit/blockstate/BlockState.java
  src/main/java/cn/nukkit/blockstate/IBlockState.java
  src/main/java/cn/nukkit/blockstate/IMutableBlockState.java
  src/main/java/cn/nukkit/item/ItemBlock.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectTree.java
Labels: Resolution: resolved, Type: bug, Type: enhancement, size/XXL

#681 Improves /debugpaste
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/command/defaults/DebugPasteCommand.java
  src/main/java/cn/nukkit/utils/Utils.java
Labels: Resolution: resolved, Type: enhancement

#677 Implement respawn anchor, block explosions, fix bed explosion, add new events, improves PlayerRespawnEvent
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBed.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockRespawnAnchor.java
  src/main/java/cn/nukkit/entity/item/EntityEndCrystal.java
  src/main/java/cn/nukkit/entity/item/EntityMinecartTNT.java
  src/main/java/cn/nukkit/entity/item/EntityPrimedTNT.java
  src/main/java/cn/nukkit/event/block/BlockExplodeEvent.java
  src/main/java/cn/nukkit/event/block/BlockExplosionPrimeEvent.java
  src/main/java/cn/nukkit/event/entity/EntityExplodeEvent.java
  src/main/java/cn/nukkit/event/entity/EntityExplosionPrimeEvent.java
  src/main/java/cn/nukkit/event/player/PlayerRespawnEvent.java
  src/main/java/cn/nukkit/level/Explosion.java
Labels: Implementation: Block, Resolution: resolved, Type: enhancement, size/L

#966 Fixes: Direction is part of item meta of the anvil block
  src/main/java/cn/nukkit/block/BlockAnvil.java
Labels: Implementation: Block, Resolution: resolved, Type: bug, size/XS

#958 Prevent attack oneself hack
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/event/player/PlayerKickEvent.java
Labels: Implementation: Entity, Resolution: resolved, Tag : RakNet, Type: enhancement, size/XS

#968 Fixes github actions
  .github/ISSUE_TEMPLATE/0-bug-report.md
  .github/ISSUE_TEMPLATE/2-compatibility-report.md
  .github/ISSUE_TEMPLATE/3-question.md
  .github/ISSUE_TEMPLATE/4-discussion.md
  .github/workflows/github-publish.yml
Labels: Type: Tool

#969 Fixes github actions
  .github/ISSUE_TEMPLATE/0-bug-report.md
  .github/ISSUE_TEMPLATE/2-compatibility-report.md
  .github/ISSUE_TEMPLATE/3-question.md
  .github/ISSUE_TEMPLATE/4-discussion.md
  .github/workflows/github-publish-snapshot.yml
Labels: Resolution: resolved, Type: Tool
