Repository PowerNukkit/PowerNukkit, pull requests merged in 2021-07, with the labels that each got.

#961 Fix and Improve Food Eating
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/item/Item.java
  src/main/java/cn/nukkit/item/ItemEdible.java
  src/main/java/cn/nukkit/item/food/Food.java
Labels: Implementation: Item, Status: Awaiting Merge, Type: bug, Type: enhancement, size/S

#1153 Fixes some sonar reports and deprecates BlockNetherBrick
  src/main/java/cn/nukkit/api/PowerNukkitDifference.java
  src/main/java/cn/nukkit/block/BlockBricksRedNether.java
  src/main/java/cn/nukkit/block/BlockNetherBrick.java
Labels: Type: bug

#1121 Let's keep a change log
  CHANGELOG.md
Labels: Type: Tool

#1187 Fixes powered rails do not update in a row
  src/main/java/cn/nukkit/block/BlockRailPowered.java
Labels: Status: Awaiting Merge, Tag: Redstone, Type: bug, size/XS

#1191 Fixes: SimpleChunkManager.setBlockAtLayer ignoring the layer
  src/main/java/cn/nukkit/level/generator/SimpleChunkManager.java
Labels: Resolution: resolved, Type: bug

#1189 Added Nether Fungi Generation via Bonemeal
  src/main/java/cn/nukkit/block/BlockFungusCrimson.java
  src/main/java/cn/nukkit/block/BlockFungusWarped.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectCrimsonTree.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectNetherTree.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectWarpedTree.java
Labels: Implementation: Block, Implementation: Item, Status: Awaiting Merge, Tag: Generation, Type: enhancement, size/S

#1199 Revert "Merge pull request #1189 from FlamingKnight/new-nether-fungi"
  src/main/java/cn/nukkit/block/BlockFungusCrimson.java
  src/main/java/cn/nukkit/block/BlockFungusWarped.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectCrimsonTree.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectNetherTree.java
  src/main/java/cn/nukkit/level/generator/object/tree/ObjectWarpedTree.java
Labels: Resolution: resolved

#1203 Fixes #1200 log and many other recipes not working
  src/main/resources/recipes.json
Labels: Resolution: resolved, Tag : Minecraft Version Update, Type: bug

#1202 Improves unknown item handling, shows unknown block instead of disconnections
  src/main/java/cn/nukkit/utils/BinaryStream.java
  src/test/java/cn/nukkit/utils/BinaryStreamTest.java
Labels: Resolution: resolved, Type: bug

#1214 Fixed the names for BlockConcrete and BlockConcretePowder
  src/main/java/cn/nukkit/block/BlockConcrete.java
  src/main/java/cn/nukkit/block/BlockConcretePowder.java
Labels: Status: Awaiting Response, Type: bug, size/S
