Repository PowerNukkit/PowerNukkit, pull requests merged in 2021-09, with the labels that each got.

#1205 Add all deepslate related blocks and some fixes
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockBricksDeepslate.java
  src/main/java/cn/nukkit/block/BlockBricksDeepslateCracked.java
  src/main/java/cn/nukkit/block/BlockDeepslateChiseled.java
  src/main/java/cn/nukkit/block/BlockDoubleSlabBrickDeepslate.java
  src/main/java/cn/nukkit/block/BlockDoubleSlabDeepslatePolished.java
  src/main/java/cn/nukkit/block/BlockDoubleSlabTileDeepslate.java
  src/main/java/cn/nukkit/block/BlockInfestedDeepslate.java
  src/main/java/cn/nukkit/block/BlockMonsterEgg.java
  src/main/java/cn/nukkit/block/BlockSlabBrickDeepslate.java
  src/main/java/cn/nukkit/block/BlockSlabDeepslatePolished.java
  src/main/java/cn/nukkit/block/BlockSlabTileDeepslate.java
  src/main/java/cn/nukkit/block/BlockStairsBrickDeepslate.java
  src/main/java/cn/nukkit/block/BlockStairsDeepslateCobbled.java
  src/main/java/cn/nukkit/block/BlockStairsDeepslatePolished.java
  src/main/java/cn/nukkit/block/BlockStairsTileDeepslate.java
  src/main/java/cn/nukkit/block/BlockTilesDeepslate.java
  src/main/java/cn/nukkit/block/BlockTilesDeepslateCracked.java
  src/main/java/cn/nukkit/block/BlockWallBrickDeepslate.java
  src/main/java/cn/nukkit/block/BlockWallDeepslateCobbled.java
  src/main/java/cn/nukkit/block/BlockWallDeepslatePolished.java
  src/main/java/cn/nukkit/block/BlockWallTileDeepslate.java
Labels: Type: enhancement, Status: Awaiting Review, Implementation: Block, size/L, Merge Type : Squash

#1193 Add missing damage causes and improve magma block death message
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/block/BlockMagma.java
  src/main/java/cn/nukkit/event/entity/EntityDamageEvent.java
Labels: Status: Awaiting Review, Tag: i11n, size/S

#1231 Add support for the Minecraft 1.17.30 protocol(465)
  src/main/java/cn/nukkit/entity/data/Skin.java
  src/main/java/cn/nukkit/network/protocol/CraftingDataPacket.java
  src/main/java/cn/nukkit/network/protocol/HurtArmorPacket.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
  src/main/java/cn/nukkit/utils/BinaryStream.java
  src/main/resources/canonical_block_states.nbt
  src/main/resources/creativeitems.json
Labels: Type: enhancement, Status: In Progress, Tag : Minecraft Version Update, size/M, Needs: Ingame Testing
