Repository PowerNukkit/PowerNukkit, pull requests merged in 2022-02, with the labels that each got.

#1303 Fix nametag being applied on adventure mode (#1298)
  src/main/java/cn/nukkit/entity/EntityCreature.java
  src/main/java/cn/nukkit/entity/EntityNameable.java
Labels: Status: Awaiting Review, Implementation: Entity, size/XS, Needs: Ingame Testing, priority:1

#1295 Correction of efficiency in Block.java
  src/main/java/cn/nukkit/block/Block.java
Labels: Type: enhancement, Resolution: resolved, size/XS, priority:1

#1194 Implement isIgnoringMobEquipmentPacket to fix book signing and fix BookEditPacket handler
  src/main/java/cn/nukkit/Player.java
Labels: Type: bug, Resolution: resolved, Implementation: Item, size/XS, priority:1

#1324 Fix speed potion duration
  src/main/java/cn/nukkit/potion/Potion.java
Labels: good first issue, Resolution: resolved, size/XS, Merge Type : Squash, priority:2

#1314 Bump protocol + Miscelaneous Fixes
  dumps/block-properties.ini
  dumps/block-states.ini
  dumps/item-id-dump.properties
  dumps/runtime_block_states.dat.dump.txt
  dumps/simple-blocks-nukkit.txt
  src/main/java/cn/nukkit/block/BlockMagma.java
  src/main/java/cn/nukkit/block/BlockSkull.java
  src/main/java/cn/nukkit/entity/Entity.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/inventory/RecipeType.java
  src/main/java/cn/nukkit/inventory/SmithingRecipe.java
  src/main/java/cn/nukkit/level/biome/Biome.java
  src/main/java/cn/nukkit/level/format/anvil/Anvil.java
  src/main/java/cn/nukkit/level/format/anvil/util/BlockStorage.java
  src/main/java/cn/nukkit/level/util/PalettedBlockStorage.java
  src/main/java/cn/nukkit/network/protocol/BossEventPacket.java
  src/main/java/cn/nukkit/network/protocol/CraftingDataPacket.java
  src/main/java/cn/nukkit/network/protocol/LevelChunkPacket.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
  src/main/resources/biome_definitions.dat
  src/main/resources/biome_id_map.json
  src/main/resources/canonical_block_states.nbt
  src/main/resources/creative_items.json
  src/main/resources/creativeitems.json
  src/main/resources/entity_identifiers.dat
  src/main/resources/recipes.json
  src/main/resources/runtime_item_ids.json
  src/main/resources/runtime_item_states.json
  src/test/java/org/powernukkit/updater/AllResourceUpdater.java
  src/test/resources/org/powernukkit/updater/dumps/pmmp/required_item_list.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/creativeitems.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/recipes.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/runtime_item_states.json
Labels: Status: Awaiting Review, Tag : Minecraft Version Update, Status: Waiting for Code Owner, size/M, Needs: Ingame Testing, priority:0
