Repository PowerNukkit/PowerNukkit, pull requests merged in 2022-07, with the labels that each got.

#1367 Update hunger exhaustion levels for 1.18.30
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/PlayerFood.java
Labels: Status: Awaiting Review, size/XS, priority:1

#1356 Add support for WaterdogPE xuid and IP
  src/main/java/cn/nukkit/Player.java
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/network/RakNetInterface.java
  src/main/java/cn/nukkit/utils/ClientChainData.java
  src/main/java/cn/nukkit/utils/LoginChainData.java
  src/main/resources/default-nukkit.yml
  src/test/java/cn/nukkit/network/RakNetInterfaceTest.java
Labels: Type: enhancement, Status: Awaiting Review, Status: Waiting for Code Owner, size/S, priority:1

#1370 Improve waterdog support
  src/main/java/cn/nukkit/Server.java
  src/main/java/cn/nukkit/utils/ClientChainData.java
Labels: size/S, Tag: Code Quality

#1380 Fix dispenser dispense potions without data and implement lingering potion dispense
  src/main/java/cn/nukkit/dispenser/DispenseBehaviorRegister.java
  src/main/java/cn/nukkit/dispenser/ProjectileDispenseBehavior.java
  src/main/java/cn/nukkit/entity/item/EntityPotion.java
  src/main/java/cn/nukkit/entity/item/EntityPotionLingering.java
  src/main/java/cn/nukkit/item/ItemPotionLingering.java
  src/main/java/cn/nukkit/item/ItemPotionSplash.java
Labels: Type: bug, Type: enhancement, Status: Needs Testing, size/S, priority:2, Type: Missing Feature

#1379 Fix huge mushroom blocks drops
  src/main/java/cn/nukkit/block/BlockHugeMushroomBrown.java
  src/main/java/cn/nukkit/block/BlockHugeMushroomRed.java
Labels: Type: bug, size/S, priority:2, Status: Awaiting In Game Testing

#1388 Update to Minecraft v1.19.10 (Protocol v534)
  src/main/java/cn/nukkit/block/BlockLapis.java
  src/main/java/cn/nukkit/inventory/CraftingManager.java
  src/main/java/cn/nukkit/network/protocol/AddEntityPacket.java
  src/main/java/cn/nukkit/network/protocol/AddPlayerPacket.java
  src/main/java/cn/nukkit/network/protocol/EntityEventPacket.java
  src/main/java/cn/nukkit/network/protocol/LevelSoundEventPacket.java
  src/main/java/cn/nukkit/network/protocol/PlayStatusPacket.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
  src/main/resources/creativeitems.json
  src/main/resources/entity_identifiers.dat
  src/main/resources/recipes.json
  src/main/resources/runtime_item_ids.json
  src/test/resources/org/powernukkit/updater/dumps/pmmp/required_item_list.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/creativeitems.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/recipes.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/runtime_item_states.json
Labels: Status: Awaiting Review, Tag : Minecraft Version Update, size/M, Needs: Ingame Testing, priority:0

#1387 Remove check for waterlogged blocks on `BlockFallable`
  src/main/java/cn/nukkit/block/BlockFallable.java
Labels: Status: Awaiting Review, Implementation: Block, size/XS, Tag: Entity, priority:1

#1377 Fix spider eye cannot be eaten (#1366)
  src/main/java/cn/nukkit/item/ItemSpiderEye.java
  src/main/java/cn/nukkit/item/food/Food.java
Labels: Status: Awaiting Merge, Implementation: Item, size/XS, Merge Type : Squash, priority:3
