Repository PowerNukkit/PowerNukkit, pull requests merged in 2022-04, with the labels that each got.

#1327 Fix command whitelist output
  src/main/java/cn/nukkit/command/defaults/WhitelistCommand.java
Labels: Resolution: resolved, size/XS, priority:3

#1338 Add support to Minecraft 1.18.30
  UPGRADING_TO_NEXT_MINECRAFT.md
  dumps/block-states.ini
  dumps/runtime_block_states.dat.dump.txt
  dumps/simple-blocks-nukkit.txt
  pom.xml
  src/main/java/cn/nukkit/block/Block.java
  src/main/java/cn/nukkit/block/BlockID.java
  src/main/java/cn/nukkit/block/BlockPiston.java
  src/main/java/cn/nukkit/block/BlockPistonHead.java
  src/main/java/cn/nukkit/block/BlockPistonHeadSticky.java
  src/main/java/cn/nukkit/block/BlockPistonSticky.java
  src/main/java/cn/nukkit/block/BlockTripWire.java
  src/main/java/cn/nukkit/block/BlockTripWireHook.java
  src/main/java/cn/nukkit/blockentity/BlockEntityPistonArm.java
  src/main/java/cn/nukkit/item/ItemString.java
  src/main/java/cn/nukkit/level/DimensionData.java
  src/main/java/cn/nukkit/level/DimensionEnum.java
  src/main/java/cn/nukkit/level/Level.java
  src/main/java/cn/nukkit/level/format/anvil/Anvil.java
  src/main/java/cn/nukkit/level/format/generic/serializer/NetworkChunkSerializer.java
  src/main/java/cn/nukkit/level/generator/Generator.java
  src/main/java/cn/nukkit/network/protocol/AddPlayerPacket.java
  src/main/java/cn/nukkit/network/protocol/ProtocolInfo.java
  src/main/java/cn/nukkit/network/protocol/SpawnParticleEffectPacket.java
  src/main/java/cn/nukkit/network/protocol/StartGamePacket.java
  src/main/resources/block_ids.csv
  src/main/resources/canonical_block_states.nbt
  src/main/resources/creative_items.json
  src/main/resources/creativeitems.json
  src/main/resources/entity_identifiers.dat
  src/main/resources/legacy_item_ids.json
  src/main/resources/recipes.json
  src/main/resources/runtime_item_ids.json
  src/main/resources/runtime_item_states.json
  src/test/java/org/powernukkit/updater/AllResourceUpdater.java
  src/test/java/org/powernukkit/updater/AllResourcesDownloader.java
  src/test/resources/org/powernukkit/updater/dumps/pmmp/required_item_list.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/creativeitems.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/recipes.json
  src/test/resources/org/powernukkit/updater/dumps/proxypass/runtime_item_states.json
Labels: Type: enhancement, Resolution: resolved, Tag : Minecraft Version Update, size/M, Tag : RakNet, Tag: Upstream, priority:0

#1336 Stair fix for #696
  src/main/java/cn/nukkit/block/BlockStairs.java
Labels: Type: bug, Resolution: resolved

#1344 Backward compatibility fix with AntiXRay PowerNukkit port.
  CHANGELOG.md
  pom.xml
  src/main/java/cn/nukkit/level/util/PalettedBlockStorage.java
Labels: Type: backwards compatibility

#1326 Fix falling blocks in bubbles
  src/main/java/cn/nukkit/block/BlockBubbleColumn.java
  src/main/java/cn/nukkit/entity/item/EntityFallingBlock.java
Labels: Type: enhancement, Status: Awaiting Review, Status: Needs Testing, size/S, Tag: Entity, Needs: Ingame Testing
